"""Regenerate LibraryData.luau (the fake asset library the skin tests use) from
Roblox/catalog.json, so new pack assets are testable before they're imported.

    python tests/skins/make_library_data.py
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))


def num(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def vec(vals):
    return "{" + ",".join(num(v) for v in vals) + "}"


def main():
    recs = json.load(open(os.path.join(ROOT, "Roblox", "catalog.json")))
    out = []
    for r in recs:
        if r["category"] == "Scenes" or "size_studs_roblox_XYZ" not in r:
            continue
        parts = ",".join(
            "{name=%s,size=%s,oo=%s,place=%s}" % (json.dumps(p["name"]), vec(p["size_studs_roblox_XYZ"]),
                                                  vec(p["origin_offset"]), vec(p["placement_cframe"]))
            for p in r.get("parts", []))
        out.append("{name=%s,kind=%s,cat=%s,size=%s,oo=%s,parts={%s},r15=%s}" % (
            json.dumps(r["name"]), json.dumps(r["kind"]), json.dumps(r["category"]),
            vec(r["size_studs_roblox_XYZ"]), vec(r["origin_offset"]), parts,
            json.dumps(r.get("meta", {}).get("r15_attachment", ""))))
    path = os.path.join(HERE, "LibraryData.luau")
    with open(path, "w") as f:
        f.write("-- Generated by tests/skins/make_library_data.py from Roblox/catalog.json\n")
        f.write("return {" + ",".join(out) + "}\n")
    print(f"{len(out)} assets -> {path}")


if __name__ == "__main__":
    main()
