"""Generate src/shared/Models.luau from models/catalog.json (written by
blender/build.py) and models/uploaded_ids.json (written by tools/upload_models.py).

    python3 tools/gen_models.py

Models without an uploaded id get Id = nil: the game draws those with parts.
"""
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def num(v):
    s = f"{v:.3f}".rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def vec(v):
    return "{ " + ", ".join(num(x) for x in v) + " }"


def main():
    catalog = json.load(open(os.path.join(ROOT, "models", "catalog.json")))
    ids_path = os.path.join(ROOT, "models", "uploaded_ids.json")
    ids = json.load(open(ids_path)) if os.path.exists(ids_path) else {}
    lines = [
        "--!strict",
        "-- GENERATED by tools/gen_models.py from models/catalog.json + models/uploaded_ids.json.",
        "-- Every 3D model built by blender/build.py: its size and pivot offset (pivot minus",
        "-- bounding-box centre) in studs, Roblox axes. Id is the uploaded Roblox model asset",
        "-- (nil until uploaded: the game then draws that thing with parts instead).",
        "",
        "export type Entry = { Id: number?, Category: string, Size: { number }, Offset: { number } }",
        "",
        "local Models: { [string]: Entry } = {",
    ]
    for r in sorted(catalog, key=lambda r: r["name"]):
        i = ids.get(r["name"])
        lines.append('\t["%s"] = { Id = %s, Category = "%s", Size = %s, Offset = %s },' % (
            r["name"], str(int(i)) if i else "nil", r["category"], vec(r["size"]), vec(r["offset"])))
    lines += ["}", "", "return Models", ""]
    out = os.path.join(ROOT, "src", "shared", "Models.luau")
    open(out, "w").write("\n".join(lines))
    print(f"wrote {out}: {len(catalog)} models, {sum(1 for r in catalog if ids.get(r['name']))} uploaded")


if __name__ == "__main__":
    main()
