"""Writes assets/MANIFEST.md from the files on disk and assets/export/manifest.json.
Pure Python (no bpy). Run after blender/build.py, assets/ui/make_icons.py and
assets/audio/make_audio.py:

    python3 blender/make_manifest.py
"""

import json
import os
import struct
import wave

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
A = os.path.join(ROOT, "assets")

DESCRIPTIONS = {
    "Chicken": "White hen (default chicken)",
    "ChickenBrown": "Brown hen (colour variant)",
    "Fox": "Fox (raider)",
    "Egg": "Plain egg (single material, tint in game)",
    "LittleCoop": "Housing tier 1", "TwinCoop": "Housing tier 2", "HenHouse": "Housing tier 3",
    "RedBarn": "Housing tier 4", "BigBarn": "Housing tier 5", "PoultryHall": "Housing tier 6",
    "EggFactory": "Housing tier 7", "HenTower": "Housing tier 8", "SkyRoost": "Housing tier 9",
    "MegaDome": "Housing tier 10",
    "Warehouse": "Warehouse with loading dock", "Silo": "Egg silo",
    "FarmPickup": "Vehicle tier 1", "DeliveryVan": "Vehicle tier 2", "BoxTruck": "Vehicle tier 3",
    "EggHauler": "Vehicle tier 4 (semi truck + trailer)",
    "Farmhand": "Worker: blocky farmer (Roblox-like proportions)", "RoboPicker": "Worker: egg-picking robot",
    "Fence": "Fence segment (8 studs)", "Tree": "Tree", "Bush": "Flowering bush", "Rock": "Rock pair",
    "EggCrate": "Wooden crate of eggs", "Signboard": "Farm signboard",
}


def size(p):
    return os.path.getsize(p)


def kb(n):
    return f"{n / 1024:.0f} KB" if n < 1024 * 1024 else f"{n / 1048576:.1f} MB"


def png_dims(p):
    with open(p, "rb") as fh:
        head = fh.read(24)
    w, h = struct.unpack(">II", head[16:24])
    return f"{w}x{h}"


def main():
    with open(os.path.join(A, "export", "manifest.json")) as fh:
        meshes = json.load(fh)
    total = 0
    for dp, _, fs in os.walk(A):
        for f in fs:
            total += size(os.path.join(dp, f))
    renders_dir = os.path.join(ROOT, "docs", "renders")
    renders_total = sum(size(os.path.join(renders_dir, f)) for f in os.listdir(renders_dir))

    L = []
    L.append("# Egg Farm asset manifest\n")
    L.append("All files listed here are **original works generated by the scripts in this repository** "
             "(procedural Blender modelling, Pillow vector drawing and numpy synthesis). No third-party "
             "models, textures, fonts, images, samples or recordings were used, and nothing was imported "
             "from other projects.\n")
    L.append("**Not uploaded.** None of these assets have been uploaded to Roblox (no Asset Manager / Open "
             "Cloud step has been done). The game currently builds its models from native Parts and draws "
             "its icons natively; whether and when to upload these is the owner's decision.\n")
    L.append(f"Total size of `assets/`: {kb(total)} (plus {kb(renders_total)} of previews in `docs/renders/`).\n")

    L.append("## Regenerating\n")
    L.append("| Command | Produces |\n|---|---|")
    L.append("| `python3 blender/build.py [--only Name\\|Category] [--no-render]` | FBX + OBJ exports, `.blend` scenes, "
             "preview renders, `assets/export/manifest.json` |")
    L.append("| `python3 blender/verify.py` | Re-imports every FBX in a fresh scene; checks triangles, origin, size, OBJ twin, facing |")
    L.append("| `python3 assets/ui/make_icons.py` | `assets/ui/icons/*.png`, `assets/ui/icons_sheet.png` |")
    L.append("| `python3 assets/audio/make_audio.py` | `assets/audio/*.wav` |")
    L.append("| `python3 blender/make_manifest.py` | this file |\n")
    L.append("Model scripts: `blender/lib.py` (primitives, materials, export conventions), "
             "`blender/assets_living.py`, `blender/assets_buildings.py`, `blender/assets_vehicles.py`, "
             "`blender/assets_props.py`.\n")

    L.append("## 3D models\n")
    L.append("Conventions: one mesh per file, flat shaded, one material per flat colour (`EF_<Colour>`, no "
             "textures, no UVs needed), origin at the base centre, authored in metres with 1 stud = 0.28 m. "
             "Exported with `axis_forward='-Z', axis_up='Y'`; the model's front faces **-Z** (Roblox "
             "LookVector), checked by `verify.py`. Sizes below are W x H x D in studs; triangle budget "
             "10,000 per mesh (Roblox limit 20,000).\n")
    L.append("Each model has `assets/export/<Name>.fbx`, `assets/export/obj/<Name>.obj` (+ `.mtl`) and a "
             "preview `docs/renders/<Name>.png` (320x320). Editable scenes: `assets/blend/<Category>.blend`.\n")
    L.append("| Name | What | Category (.blend) | Triangles | Size (studs W x H x D) | Materials | FBX |")
    L.append("|---|---|---|---:|---|---:|---:|")
    tri_total = 0
    for name, m in sorted(meshes.items(), key=lambda kv: (kv[1]["category"], kv[0])):
        fbx = os.path.join(A, "export", name + ".fbx")
        desc = DESCRIPTIONS.get(name)
        if desc is None and name.startswith("Egg_"):
            desc = f"Decorated egg for egg id `{name[4:]}` (src/shared/Data/Eggs.luau)"
        w, h, d = m["studs"]
        tri_total += m["tris"]
        L.append(f"| {name} | {desc or ''} | {m['category']} | {m['tris']} | {w:g} x {h:g} x {d:g} | "
                 f"{len(m['materials'])} | {kb(size(fbx)) if os.path.exists(fbx) else 'missing'} |")
    L.append(f"\n{len(meshes)} meshes, {tri_total} triangles in total; largest is "
             f"{max(meshes.items(), key=lambda kv: kv[1]['tris'])[0]} "
             f"({max(m['tris'] for m in meshes.values())} triangles).\n")

    L.append("### Editable scenes\n")
    L.append("| File | Size |\n|---|---:|")
    for f in sorted(os.listdir(os.path.join(A, "blend"))):
        L.append(f"| `assets/blend/{f}` | {kb(size(os.path.join(A, 'blend', f)))} |")
    L.append("")

    L.append("## UI icons\n")
    L.append("Generated by `assets/ui/make_icons.py` (Pillow shapes drawn at 1024 px, downsampled). "
             "Transparent background, thick dark outline, bright flat fills. "
             "`assets/ui/icons_sheet.png` is a review contact sheet.\n")
    L.append("| File | Size | Bytes |\n|---|---|---:|")
    icons = os.path.join(A, "ui", "icons")
    for f in sorted(os.listdir(icons)):
        p = os.path.join(icons, f)
        L.append(f"| `assets/ui/icons/{f}` | {png_dims(p)} | {kb(size(p))} |")
    L.append("")

    L.append("## Audio\n")
    L.append("Generated by `assets/audio/make_audio.py` (numpy oscillators, noise, envelopes). "
             "44.1 kHz, mono, 16-bit PCM WAV.\n")
    L.append("| File | Length | What |\n|---|---:|---|")
    what = {
        "click": "UI click", "buy": "Purchase cha-ching (noise 'cha' + two bells)", "coin": "Coin blip",
        "collect": "Egg collect, bubbly pop", "deposit": "Deposit: thud + chime", "error": "Error buzz",
        "rebirth": "Rebirth rising arpeggio", "claim": "Reward claim sparkle", "spawn": "Chick spawn chirp",
        "music_loop": "Calm background loop, C-Am-F-G at 80 bpm, seamless",
    }
    audio = os.path.join(A, "audio")
    for f in sorted(os.listdir(audio)):
        if not f.endswith(".wav"):
            continue
        with wave.open(os.path.join(audio, f)) as w:
            secs = w.getnframes() / w.getframerate()
        L.append(f"| `assets/audio/{f}` | {secs:.2f} s | {what.get(f[:-4], '')} |")
    L.append("")

    L.append("## Upload notes (not done)\n")
    L.append("- Meshes: Studio **Asset Manager -> Bulk Import** or the **3D Importer** (File -> Import 3D) with "
             "the `.fbx` files; or Open Cloud `assets` API with an API key that has asset write access. "
             "Keep the import scale at the file's metres (1 stud = 0.28 m) so sizes match the table.")
    L.append("- Colours come from the materials; on import choose to keep vertex/material colours or recolour "
             "the MeshPart in game (egg variants have two materials: shell and decoration).")
    L.append("- Icons: upload as Decals/Images, then reference the `rbxassetid://` in the UI.")
    L.append("- Audio: upload WAVs via Asset Manager or Open Cloud (audio uploads need a verified account).")
    L.append("- After uploading, record the asset ids in game data; delete any Open Cloud key used.\n")

    L.append("## Licences of tools used\n")
    L.append("- Blender `bpy` 5.0.1 (GPL) used as a tool only; generated outputs are not covered by the GPL.")
    L.append("- Pillow (HPND licence) for drawing icons; numpy (BSD) for audio synthesis.")

    with open(os.path.join(A, "MANIFEST.md"), "w") as fh:
        fh.write("\n".join(L) + "\n")
    print(f"assets/ total {kb(total)}, renders {kb(renders_total)}, {len(meshes)} meshes, {tri_total} tris")


if __name__ == "__main__":
    main()
