#!/usr/bin/env python3
"""Generate src/shared/AssetIds.luau from assets/uploaded_ids.json and the export manifests.
Run after tools/upload_assets.py (it calls this). With nothing uploaded the tables are empty and
the game uses its native-part stand-ins and model-preview icons."""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(path, default):
    p = os.path.join(ROOT, path)
    return json.load(open(p)) if os.path.exists(p) else default


ids = load("assets/uploaded_ids.json", {"models": {}, "images": {}})
sizes = {}
for m in ("assets/exports/manifest.json", "assets/exports/manifest_decor.json"):
    man = load(m, {})
    for name, rec in (man.get("assets", man) if isinstance(man, dict) else {}).items():
        if isinstance(rec, dict) and "size" in rec:
            sizes[name] = rec["size"]

lines = ["--!strict", "-- GENERATED by tools/gen_asset_ids.py. Uploaded asset ids (owner's account).",
         "-- Models: size is Roblox (X width, Y height, Z depth) studs from the Blender manifest.", "return {", "\tModels = {"]
for name in sorted(ids.get("models", {})):
    s = sizes.get(name)
    if not s:
        continue
    x, y, z = s  # Blender X width, Y depth, Z height
    lines.append(f"\t\t{name} = {{ id = {ids['models'][name]['id']}, size = Vector3.new({x:.3f}, {z:.3f}, {y:.3f}) }},")
lines.append("\t},")
lines.append("\tImages = {")
for name in sorted(ids.get("images", {})):
    lines.append(f"\t\t[{json.dumps(name)}] = {ids['images'][name]['id']},")
lines += ["\t},", "} :: { Models: { [string]: { id: number, size: Vector3 } }, Images: { [string]: number } }", ""]
open(os.path.join(ROOT, "src", "shared", "AssetIds.luau"), "w").write("\n".join(lines))
print("wrote src/shared/AssetIds.luau:", len(ids.get("models", {})), "models,", len(ids.get("images", {})), "images")
