#!/usr/bin/env python3
"""Generate src/shared/Catalog.luau and docs/CATALOG.md from catalog/economy.json.

Run from the SellHotDogs folder:  python3 tools/gen_catalog.py
The JSON is the single source of truth; never hand-edit the generated files.
"""
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "catalog", "economy.json")
LUAU = os.path.join(ROOT, "src", "shared", "Catalog.luau")
MD = os.path.join(ROOT, "docs", "CATALOG.md")

IDENT = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def luau(v, ind=0):
    pad = "\t" * (ind + 1)
    if v is None:
        return "nil"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(int(v)) if float(v).is_integer() and abs(v) < 1e15 else repr(float(v))
    if isinstance(v, str):
        return json.dumps(v)
    if isinstance(v, list):
        if not v:
            return "{}"
        return "{\n" + "".join(f"{pad}{luau(x, ind + 1)},\n" for x in v) + "\t" * ind + "}"
    if isinstance(v, dict):
        if not v:
            return "{}"
        out = []
        for k, x in v.items():
            key = k if IDENT.match(k) else "[" + json.dumps(k) + "]"
            out.append(f"{pad}{key} = {luau(x, ind + 1)},\n")
        return "{\n" + "".join(out) + "\t" * ind + "}"
    raise TypeError(type(v))


def money(v):
    if isinstance(v, str):
        return v
    if v < 1000:
        return f"${v:,.2f}"
    if v < 1e6:
        return f"${v:,.0f}"
    return f"${v:.4g}"


def main():
    with open(SRC) as f:
        data = json.load(f)
    with open(LUAU, "w") as f:
        f.write("--!nocheck\n-- GENERATED by tools/gen_catalog.py from catalog/economy.json. Do not edit by hand.\n")
        f.write("-- Every value keeps its evidence status (observed/secondary/hypothesis/placeholder).\n")
        f.write("return " + luau(data) + " :: any\n")

    rows, unresolved = [], []

    def add(area, item, value, unit, e):
        st = e.get("status", "?")
        rows.append((area, item, value, unit, st, e.get("src", ""), e.get("note", "")))
        if st in ("placeholder", "hypothesis") or "CONFLICT" in e.get("note", ""):
            unresolved.append((area, item, value, st, e.get("note", "")))

    add("Start", "Starting cash", money(data["start"]["cash"]["value"]), "$", data["start"]["cash"])
    for o in data["stand_level_shape"]["observed"]:
        add("Hot Dog Stand", f"Base output at level {o['level']}", money(o["output"]), "$/cycle", o)
    add("Hot Dog Stand", "Output beyond level 4", "increment x1.11/level", "", data["stand_level_shape"]["extrapolate"])
    for o in data["level_costs_stand"]["observed"]:
        add("Hot Dog Stand", f"Level upgrade #{o['index'] + 1} cost", money(o["cost"]), "$", o)
    add("Hot Dog Stand", "Level upgrade cost beyond #4", "x1.5 per level", "", data["level_costs_stand"]["extrapolate"])
    for k, e in data["generic_business"].items():
        if not k.startswith("_"):
            add("Other businesses", k, e["value"], "", e)
    for b in data["businesses"]:
        add(b["name"], f"Unlock (ref: {b['ref']})", money(b["unlock"]["value"]), "$", b["unlock"])
        if "baseOutput" in b:
            add(b["name"], "Base output", money(b["baseOutput"]["value"]), "$/cycle", b["baseOutput"])
            add(b["name"], "Cycle time", b["cycleTime"]["value"], "s", b["cycleTime"])
        for p in b["pads"]:
            eff = {"cash": f"x{p.get('mult')} cash", "speed": f"x{p.get('mult')} speed", "auto": "automates", "structure": "structure", "minigame": "unlocks minigame"}[p["kind"]]
            ref = f" (ref: {p['ref']})" if p.get("ref") else ""
            add(b["name"], f"{p['name']}{ref}: {eff}", money(p["cost"]), "$", p)
            if p.get("requires"):
                add(b["name"], f"{p['name']} requires {p['requires']}", "", "", {"status": p.get("requiresStatus", "?"), "src": "OURS", "note": "Pad order assumed sequential."})
    for k, e in data["prestige"].items():
        add("Prestige", k, e["value"] if not isinstance(e["value"], list) else ", ".join(e["value"]), "", e)
    for p in data["powers"]:
        add("Powers", f"{p['name']} investor cost by tier", ", ".join(str(c) for c in p["investorCost"]), "investors", p)
    for it in data.get("decor", {}).get("items", []):
        add("Decor (looks only)", it["name"] + " (model " + it["model"] + ")", money(it["price"]), "$", {"status": "placeholder", "src": "OURS", "note": "Sell Hot Dogs addition; kept forever; no earnings effect."})
    for k in ("cashMilestones", "levelMilestones"):
        e = data.get("progress", {}).get(k)
        if e:
            add("Progress feedback", k, json.dumps(e["value"]), "", e)
    for area in ("pickups", "phone", "dash", "offline", "names"):
        for k, e in data[area].items():
            add(area.capitalize(), k, json.dumps(e["value"]), "", e)

    with open(MD, "w") as f:
        f.write("# Sell Hot Dogs: evidence-linked catalog\n\n")
        f.write("Generated from `catalog/economy.json` by `tools/gen_catalog.py`. Statuses: **observed** (read in dated footage by the supplied research), **secondary** (wiki/guide claim, unverified), **hypothesis** (our interpretation of observations), **placeholder** (unknown; labelled stand-in so the game runs).\n\n")
        f.write("## Sources\n\n| id | source | note |\n|---|---|---|\n")
        for sid, s in data["sources"].items():
            f.write(f"| {sid} | [{s['title']}]({s['url']}) | {s['note']} |\n" if s["url"] else f"| {sid} | {s['title']} | {s['note']} |\n")
        f.write("\nTimestamps like `N 00:48.2` mean source N at video time 00:48.2.\n\n## All values\n\n| area | item | value | unit | status | source | note |\n|---|---|---|---|---|---|---|\n")
        for r in rows:
            f.write("| " + " | ".join(str(x).replace("|", "/") for x in r) + " |\n")
        f.write("\n## Robux offerings (displays only; never charged as constants)\n\n| product | kind | grants | Robux seen in footage | status/source | secondary claim | note |\n|---|---|---|---|---|---|---|\n")
        for p in data["products"]:
            f.write(f"| {p['name']} | {p['kind']} | {p['grants']} | {p.get('seenRobux', '-')} | {p.get('seenStatus', 'unknown')} {p.get('seenSrc', '')} | {p.get('secondaryRobux', '-')} | {p.get('note', '')} |\n")
        f.write("\nLive prices must come from `MarketplaceService:GetProductInfo` for the new game's own IDs (regional pricing); these numbers are historical displays from one creator's session.\n")
        f.write(f"\n## Unresolved ({len(unresolved)} entries)\n\nEvery row below is a guess or interpretation that the game currently runs on. Replace with evidence when available.\n\n| area | item | current value | status | note |\n|---|---|---|---|---|\n")
        for r in unresolved:
            f.write("| " + " | ".join(str(x).replace("|", "/") for x in r) + " |\n")
    print(f"wrote {os.path.relpath(LUAU, ROOT)} and {os.path.relpath(MD, ROOT)} ({len(rows)} rows, {len(unresolved)} unresolved)")


if __name__ == "__main__":
    sys.exit(main())
