--!strict
-- Survival Hour asset data. GENERATED by blender/make_docs.py; do not edit by hand.
-- CFrames are {x, y, z, R00, R01, R02, R10, R11, R12, R20, R21, R22} in the asset's local space.
-- Build one with CFrame.new(table.unpack(t)).

return {
	SM_Reference_Dummy_R15 = {
		Kind = "Reference",
		Category = "Reference",
		Size = {3.95, 5.25, 1.23},
		Tris = 500,
		OriginOffset = {0.0, -2.625, 0.0125},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Tree_Pine_Medium01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {11.55, 20.49, 11.38},
		Tris = 852,
		OriginOffset = {0.4555, -9.753, -0.423},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 6.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.65, 12.0, 1.65}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Pine_Medium02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {8.14, 17.47, 10.01},
		Tris = 768,
		OriginOffset = {-0.4075, -8.2665, 0.3285},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 5.1, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.43, 10.2, 1.43}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Pine_Large01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {17.54, 32.42, 15.37},
		Tris = 1020,
		OriginOffset = {0.0465, -15.7905, -0.5415},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 9.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.53, 19.2, 2.53}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Pine_Small01 = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {6.66, 10.48, 7.15},
		Tris = 692,
		OriginOffset = {0.3275, -4.7575, 0.1015},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			HarvestHit = {0.0, 1.1, -0.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 3.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.99, 6.0, 0.99}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Oak_Medium01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {15.01, 15.95, 15.3},
		Tris = 1980,
		OriginOffset = {-0.5045, -7.4035, 0.0745},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 4.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.87, 8.0, 1.87}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Oak_Medium02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {13.96, 14.65, 12.88},
		Tris = 3952,
		OriginOffset = {0.433, -6.7615, 0.2665},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 3.5, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.76, 7.0, 1.76}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Oak_Large01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {21.55, 24.74, 20.01},
		Tris = 6644,
		OriginOffset = {-0.4205, -11.8155, -0.075},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 6.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {3.3, 12.0, 3.3}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Oak_Small01 = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {5.65, 8.86, 6.34},
		Tris = 976,
		OriginOffset = {0.6535, -3.9035, 0.888},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			HarvestHit = {0.0, 1.0, -0.47, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 2.125, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.924, 4.25, 0.924}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Birch_Medium01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {5.28, 18.12, 6.6},
		Tris = 810,
		OriginOffset = {-0.104, -8.657, -0.2415},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 4.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.2, 9.6, 1.2}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Birch_Small01 = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {4.37, 10.71, 4.04},
		Tris = 818,
		OriginOffset = {-0.2585, -4.9135, 0.4705},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			HarvestHit = {0.0, 1.0, -0.37, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 2.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.768, 5.4, 0.768}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Dead_Large01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {16.3, 20.06, 15.57},
		Tris = 1100,
		OriginOffset = {0.5595, -9.4535, 0.188},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 5, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.4, 10, 2.4}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Pine_Small01_Stump = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {3.04, 1.2, 3.12},
		Tris = 214,
		OriginOffset = {0.066, -0.3, -0.107},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.45, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.99, 0.9, 0.99}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Oak_Small01_Stump = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {3.17, 1.15, 2.86},
		Tris = 214,
		OriginOffset = {0.142, -0.275, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.425, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.924, 0.85, 0.924}
			}
		},
		Parts = {

		}
	},
	SM_Tree_Birch_Small01_Stump = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {2.94, 1.1, 2.67},
		Tris = 214,
		OriginOffset = {0.132, -0.25, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.704, 0.8, 0.704}
			}
		},
		Parts = {

		}
	},
	SM_Stump_Old01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {4.11, 2.18, 4.11},
		Tris = 234,
		OriginOffset = {0.0, -0.7895, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.42, 1.6, 2.42}
			}
		},
		Parts = {

		}
	},
	SM_Stump_Old02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {3.74, 3.88, 3.74},
		Tris = 190,
		OriginOffset = {0.0, -1.6385, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.98, 2.6, 1.98}
			}
		},
		Parts = {

		}
	},
	SM_FallenLog01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {8.06, 2.29, 1.78},
		Tris = 162,
		OriginOffset = {-0.002, -1.0685, -0.054},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.7225, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8, 1.445, 1.7}
			}
		},
		Parts = {

		}
	},
	SM_FallenLog02_Hollow = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {10.88, 3.11, 2.74},
		Tris = 218,
		OriginOffset = {-0.292, -1.432, -0.042},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.1475, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {10, 2.295, 2.7}
			}
		},
		Parts = {

		}
	},
	SM_Branch01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {4.55, 0.48, 3.01},
		Tris = 112,
		OriginOffset = {-0.0125, -0.24, -0.15},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Branch02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {3.65, 0.53, 2.9},
		Tris = 332,
		OriginOffset = {-0.0145, -0.2665, -0.1125},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Sticks_Loose01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.85, 0.28, 3.06},
		Tris = 96,
		OriginOffset = {0.323, -0.1615, 0.0175},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Rock_Small01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.81, 0.61, 1.29},
		Tris = 80,
		OriginOffset = {0.027, -0.3045, 0.0005},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Rock_Small02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.53, 0.72, 1.69},
		Tris = 160,
		OriginOffset = {0.232, -0.359, -0.102},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Rock_Small03 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.8, 0.29, 2.35},
		Tris = 80,
		OriginOffset = {-0.036, -0.145, 0.047},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Boulder01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {9.54, 3.49, 6.65},
		Tris = 640,
		OriginOffset = {0.4185, -1.7455, -0.0085},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {-0.6, 1.7, 0.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.6, 3.4, 6.4}
			}
		},
		Parts = {

		}
	},
	SM_Boulder02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {6.82, 4.77, 5.87},
		Tris = 720,
		OriginOffset = {-0.1055, -2.386, 0.1895},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {-0.2, 2.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.6, 4.8, 5.4}
			}
		},
		Parts = {

		}
	},
	SM_Boulder03 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {6.86, 2.25, 5.46},
		Tris = 420,
		OriginOffset = {-0.151, -1.125, -0.2615},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {7.5, 2.6, 6.5}
			}
		},
		Parts = {

		}
	},
	SM_StoneDeposit01 = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {5.99, 2.48, 4.24},
		Tris = 592,
		OriginOffset = {-0.0195, -1.239, 0.0255},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {
			HarvestHit = {0.0, 1.2, -2.1, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {4.6, 2.0, 3.8}
			}
		},
		Parts = {

		}
	},
	SM_StoneDeposit01_Depleted = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {4.38, 0.75, 4.48},
		Tris = 180,
		OriginOffset = {-0.413, -0.374, -0.169},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.35, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {4.6, 0.7, 3.8}
			}
		},
		Parts = {

		}
	},
	SM_FiberPlant01 = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {1.93, 3.79, 1.95},
		Tris = 600,
		OriginOffset = {-0.0025, -1.8255, -0.109},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			HarvestHit = {0.0, 1.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_FiberPlant01_Harvested = {
		Kind = "Harvestable",
		Category = "Forest",
		Size = {0.52, 0.65, 0.81},
		Tris = 100,
		OriginOffset = {-0.0865, -0.258, -0.0475},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Grass_Clump01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.23, 1.47, 1.35},
		Tris = 140,
		OriginOffset = {-0.1845, -0.663, -0.074},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Grass_Clump02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.6, 1.17, 1.28},
		Tris = 240,
		OriginOffset = {0.0785, -0.5135, -0.2845},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Grass_Clump03 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.34, 2.03, 1.14},
		Tris = 160,
		OriginOffset = {-0.098, -0.944, 0.031},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Bush01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.85, 2.02, 3.44},
		Tris = 416,
		OriginOffset = {-0.1695, -1.011, 0.1825},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Bush02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {4.54, 2.75, 4.53},
		Tris = 496,
		OriginOffset = {-0.291, -1.3755, -0.0635},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Bush03_Berry = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {3.26, 1.84, 3.14},
		Tris = 656,
		OriginOffset = {-0.124, -0.9205, -0.044},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Fern01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {3.98, 0.74, 3.94},
		Tris = 420,
		OriginOffset = {0.034, -0.3715, -0.126},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Fern02 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.75, 0.74, 2.85},
		Tris = 300,
		OriginOffset = {-0.111, -0.3715, 0.023},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Mushrooms01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.47, 0.93, 1.02},
		Tris = 260,
		OriginOffset = {-0.0425, -0.464, 0.002},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Mushrooms02_Glow = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.03, 0.65, 0.49},
		Tris = 176,
		OriginOffset = {0.1195, -0.327, 0.2565},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Glow = {0.0, 0.5, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_LeafLitter01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {6.08, 0.19, 4.96},
		Tris = 320,
		OriginOffset = {0.018, -0.094, -0.0535},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pinecones01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.67, 0.3, 2.24},
		Tris = 120,
		OriginOffset = {0.2195, -0.1185, 0.0315},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_MossPatch01 = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {4.67, 0.16, 3.62},
		Tris = 80,
		OriginOffset = {-0.032, -0.0775, 0.0285},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Landmark_StandingStones = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {17.26, 7.9, 17.79},
		Tris = 1060,
		OriginOffset = {0.366, -3.9485, 0.012},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {-8.0, 2.9807, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.2, 5.9614, 2.2}
			},
			{
				CFrame = {-4.9879, 2.9533, 6.2547, 0.6235, 0.0, 0.7818, 0.0, 1.0, 0.0, -0.7818, 0.0, 0.6235},
				Size = {2.2, 5.9066, 2.2}
			},
			{
				CFrame = {1.7802, 3.9944, 7.7994, -0.2225, 0.0, 0.9749, 0.0, 1.0, 0.0, -0.9749, 0.0, -0.2225},
				Size = {2.2, 7.9887, 2.2}
			},
			{
				CFrame = {7.2078, 1.5, 3.4711, -0.901, 0.0, 0.4339, 0.0, 1.0, 0.0, -0.4339, 0.0, -0.901},
				Size = {2.2, 3.0, 2.2}
			},
			{
				CFrame = {7.2078, 3.2968, -3.4711, -0.901, 0.0, -0.4339, 0.0, 1.0, 0.0, 0.4339, 0.0, -0.901},
				Size = {2.2, 6.5935, 2.2}
			},
			{
				CFrame = {1.7802, 3.5081, -7.7994, -0.2225, 0.0, -0.9749, 0.0, 1.0, 0.0, 0.9749, 0.0, -0.2225},
				Size = {2.2, 7.0162, 2.2}
			},
			{
				CFrame = {-4.9879, 2.7786, -6.2547, 0.6235, 0.0, -0.7818, 0.0, 1.0, 0.0, 0.7818, 0.0, 0.6235},
				Size = {2.2, 5.5573, 2.2}
			}
		},
		Parts = {

		}
	},
	SM_Landmark_AntlerTotem = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {3.32, 8.86, 1.19},
		Tris = 436,
		OriginOffset = {-0.001, -4.1215, 0.0325},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 3.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.2, 6.6, 1.2}
			}
		},
		Parts = {

		}
	},
	SM_Landmark_GiantLog = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {22.8, 8.6, 7.43},
		Tris = 436,
		OriginOffset = {0.0, -3.491, -0.1555},
		CollisionFidelity = "Default",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 3.06, 3.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {22, 6.12, 0.8}
			},
			{
				CFrame = {0.0, 3.06, -3.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {22, 6.12, 0.8}
			},
			{
				CFrame = {0.0, 6.26, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {22, 0.8, 6.8}
			}
		},
		Parts = {

		}
	},
	SM_Clearing_GroundPatch = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {40.0, 0.65, 40.0},
		Tris = 1152,
		OriginOffset = {0.0, 0.275, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Camp_LogBench = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {5.0, 1.89, 1.26},
		Tris = 132,
		OriginOffset = {0.0, -0.945, -0.0195},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.85, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {5, 1.7, 1.4}
			}
		},
		Parts = {

		}
	},
	SM_Camp_FirewoodStack = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.65, 1.76, 1.5},
		Tris = 180,
		OriginOffset = {0.0, -0.88, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {3.0, 1.8, 1.5}
			}
		},
		Parts = {

		}
	},
	SM_Camp_DryingRack = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {4.6, 4.23, 1.41},
		Tris = 180,
		OriginOffset = {0.0, -1.9, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {4.4, 4, 1.4}
			}
		},
		Parts = {

		}
	},
	SM_Camp_Lantern = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.36, 5.3, 0.64},
		Tris = 190,
		OriginOffset = {0.54, -2.35, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Light = {-0.9, 4.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 2.5, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.4, 5, 0.4}
			}
		},
		Parts = {

		}
	},
	SM_Camp_Bedroll = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {1.8, 0.71, 4.6},
		Tris = 212,
		OriginOffset = {0.0, -0.3, 0.0},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Camp_Barrel = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.0, 2.53, 2.0},
		Tris = 304,
		OriginOffset = {0.0, -1.265, 0.0},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.25, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2, 2.5, 2}
			}
		},
		Parts = {

		}
	},
	SM_Camp_ChoppingBlock = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {3.8, 1.7, 3.84},
		Tris = 238,
		OriginOffset = {0.002, -0.55, 0.004},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.76, 1.4, 1.76}
			}
		},
		Parts = {

		}
	},
	SM_Camp_TeamBanner = {
		Kind = "WorldProp",
		Category = "Forest",
		Size = {2.29, 9.4, 0.39},
		Tris = 104,
		OriginOffset = {0.9525, -4.3, 0.0},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 4.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.35, 8.6, 0.35}
			}
		},
		Parts = {

		}
	},
	SM_Stream_Straight = {
		Kind = "WorldProp",
		Category = "Stream",
		Size = {24.0, 4.05, 16.0},
		Tris = 1356,
		OriginOffset = {0.0, 0.575, 0.0},
		CollisionFidelity = "Default",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Stream_Bend90 = {
		Kind = "WorldProp",
		Category = "Stream",
		Size = {28.0, 3.8, 28.0},
		Tris = 1736,
		OriginOffset = {-2.0, 0.7, -6.0},
		CollisionFidelity = "Default",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Stream_PoolEnd = {
		Kind = "WorldProp",
		Category = "Stream",
		Size = {24.0, 3.8, 24.0},
		Tris = 2576,
		OriginOffset = {0.0, 0.7, -4.0},
		CollisionFidelity = "Default",
		TeamColored = false,
		Attachments = {
			Refill = {0.0, -0.6, 7, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Stream_Water_Straight = {
		Kind = "Effect",
		Category = "Stream",
		Size = {10.5, 0.1, 16.0},
		Tris = 176,
		OriginOffset = {0.0, 0.65, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Stream_Water_Bend90 = {
		Kind = "Effect",
		Category = "Stream",
		Size = {21.25, 0.1, 21.25},
		Tris = 256,
		OriginOffset = {-5.375, 0.65, -2.625},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Stream_Water_PoolEnd = {
		Kind = "Effect",
		Category = "Stream",
		Size = {12.4, 0.1, 21.2},
		Tris = 172,
		OriginOffset = {0.0, 0.65, -2.6},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_StreamRocks01 = {
		Kind = "WorldProp",
		Category = "Stream",
		Size = {3.24, 0.64, 3.38},
		Tris = 400,
		OriginOffset = {0.4485, -0.3185, 0.289},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_StreamRocks02 = {
		Kind = "WorldProp",
		Category = "Stream",
		Size = {7.58, 1.59, 2.25},
		Tris = 240,
		OriginOffset = {0.0105, -0.793, 0.168},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {2.6, 0.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.0, 1.6, 1.8}
			},
			{
				CFrame = {0.0, 0.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.0, 1.6, 1.8}
			},
			{
				CFrame = {-2.6, 0.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.0, 1.6, 1.8}
			}
		},
		Parts = {

		}
	},
	SM_StreamRocks03 = {
		Kind = "WorldProp",
		Category = "Stream",
		Size = {3.01, 0.2, 4.23},
		Tris = 240,
		OriginOffset = {0.543, -0.1, -0.1685},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Campfire_Burning = {
		Kind = "Structure",
		Category = "Camp",
		Size = {6.81, 6.5, 6.44},
		Tris = 1202,
		OriginOffset = {0.247, -2.95, 0.004},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Fire = {0.0, 0.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Smoke = {0.0, 3.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Light = {0.0, 2.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Extinguish = {0.0, 1.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			WaterTarget = {0.0, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			TeamFlag = {-2.1, 6.3, 2.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.45, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.4, 0.9, 6.4}
			}
		},
		Parts = {

		}
	},
	SM_Campfire_Extinguished = {
		Kind = "Structure",
		Category = "Camp",
		Size = {6.96, 6.5, 6.62},
		Tris = 1378,
		OriginOffset = {0.169, -2.95, 0.042},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Fire = {0.0, 0.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Smoke = {0.0, 3.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Light = {0.0, 2.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Extinguish = {0.0, 1.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			WaterTarget = {0.0, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			TeamFlag = {-2.1, 6.3, 2.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.45, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.4, 0.9, 6.4}
			}
		},
		Parts = {

		}
	},
	SM_Campfire_ColdWet = {
		Kind = "Structure",
		Category = "Camp",
		Size = {6.96, 6.5, 6.76},
		Tris = 1254,
		OriginOffset = {0.1725, -2.95, 0.0305},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Fire = {0.0, 0.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Smoke = {0.0, 3.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Light = {0.0, 2.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Extinguish = {0.0, 1.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			WaterTarget = {0.0, 0.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			TeamFlag = {-2.1, 6.3, 2.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.45, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.4, 0.9, 6.4}
			}
		},
		Parts = {

		}
	},
	SM_Campfire_Flames = {
		Kind = "Effect",
		Category = "Camp",
		Size = {2.47, 4.9, 2.42},
		Tris = 48,
		OriginOffset = {0.2055, -2.7, -0.053},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Campfire_WaterTarget = {
		Kind = "Effect",
		Category = "Camp",
		Size = {6.4, 0.44, 6.4},
		Tris = 272,
		OriginOffset = {0.0, -0.35, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Workbench_Level01 = {
		Kind = "Structure",
		Category = "Camp",
		Size = {6.0, 3.46, 2.44},
		Tris = 460,
		OriginOffset = {0.0, -1.73, 0.0},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Craft = {0.0, 2.75, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Prompt = {0.0, 3.6, -1.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.0, 2.8, 2.6}
			}
		},
		Parts = {

		}
	},
	SM_Workbench_Level02 = {
		Kind = "Structure",
		Category = "Camp",
		Size = {7.0, 6.4, 3.62},
		Tris = 692,
		OriginOffset = {0.0, -3.2, 0.2875},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Craft = {0.0, 3.0, -0.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Prompt = {0.0, 4.2, -1.9, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.5, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {7.0, 3.0, 3.0}
			},
			{
				CFrame = {0.0, 4.7, 1.35, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.8, 3.4, 0.4}
			}
		},
		Parts = {

		}
	},
	SM_Workbench_Level03 = {
		Kind = "Structure",
		Category = "Camp",
		Size = {10.09, 7.8, 3.5},
		Tris = 1040,
		OriginOffset = {-1.044, -3.9, 0.0},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Craft = {0.0, 3.1, -0.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Prompt = {0.0, 4.3, -2.1, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.55, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.0, 3.1, 3.4}
			},
			{
				CFrame = {5.3, 1.2, -0.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.6, 2.4, 1.6}
			},
			{
				CFrame = {0.0, 5.2, 1.55, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.0, 4.8, 0.5}
			}
		},
		Parts = {

		}
	},
	SM_WoodenWall = {
		Kind = "Structure",
		Category = "Crafting_L1",
		Size = {8.59, 10.13, 1.56},
		Tris = 872,
		OriginOffset = {-0.3955, -4.7625, -0.0895},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			SnapLeft = {4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SnapRight = {-4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.3, 3.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.7, 7.6, 1.4}
			}
		},
		Parts = {

		}
	},
	SM_WoodenWall_Damaged = {
		Kind = "Structure",
		Category = "Crafting_L1",
		Size = {8.59, 10.14, 1.56},
		Tris = 706,
		OriginOffset = {-0.3955, -4.7625, -0.0895},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.3, 3.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.7, 7.6, 1.4}
			}
		},
		Parts = {

		}
	},
	SM_WallPost = {
		Kind = "Structure",
		Category = "Crafting_L1",
		Size = {1.42, 10.13, 1.42},
		Tris = 148,
		OriginOffset = {0.0, -4.765, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 4.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.3, 8.4, 1.3}
			}
		},
		Parts = {

		}
	},
	SM_StoneAxe = {
		Kind = "Equippable",
		Category = "Crafting_L1",
		Size = {0.48, 3.46, 1.58},
		Tris = 528,
		OriginOffset = {0.0, -1.0285, 0.2775},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Hit = {0.0, 2.3, -0.85, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_StorageBox = {
		Kind = "Structure",
		Category = "Crafting_L1",
		Size = {3.13, 1.8, 2.02},
		Tris = 816,
		OriginOffset = {0.015, -0.9, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Prompt = {0.0, 2.2, -1.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Contents = {0.0, 0.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {3.0, 1.8, 2.0}
			}
		},
		Parts = {
			SM_StorageBox_Lid = {
				Placement = {0.0, 1.8, 1.05, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, -0.0525, 1.035},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.12, -1.05, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {3.1, 0.25, 2.1}
					}
				}
			}
		}
	},
	SM_StorageBox_Damaged = {
		Kind = "Structure",
		Category = "Crafting_L1",
		Size = {3.13, 1.8, 2.02},
		Tris = 784,
		OriginOffset = {0.015, -0.9, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {3.0, 1.8, 2.0}
			}
		},
		Parts = {
			SM_StorageBox_Lid_Damaged = {
				Placement = {0.0, 1.8, 1.05, 0.9986, 0.0073, 0.0518, 0.0, 0.9903, -0.1392, -0.0523, 0.139, 0.9889},
				OriginOffset = {0.0, -0.0895, 1.035},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.12, -1.05, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {3.1, 0.25, 2.1}
					}
				}
			}
		}
	},
	SM_Spear = {
		Kind = "Equippable",
		Category = "Crafting_L1",
		Size = {0.53, 1.01, 7.21},
		Tris = 270,
		OriginOffset = {0.0155, 0.3425, 1.203},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Tip = {0.0, 0.0, -4.85, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SecondHand = {0.0, 0.0, 1.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_RepairHammer = {
		Kind = "Equippable",
		Category = "Crafting_L1",
		Size = {0.81, 3.19, 1.5},
		Tris = 362,
		OriginOffset = {0.0, -0.8935, 0.2495},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Hit = {0.0, 2.1, -1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Debris_Splinters = {
		Kind = "Debris",
		Category = "Crafting_L1",
		Size = {1.6, 0.18, 1.6},
		Tris = 32,
		OriginOffset = {-0.001, -0.17, 0.0005},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Debris_LogChunk = {
		Kind = "Debris",
		Category = "Crafting_L1",
		Size = {2.1, 0.97, 0.95},
		Tris = 42,
		OriginOffset = {0.25, -0.5, -0.025},
		CollisionFidelity = "Hull",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Debris_MetalBand = {
		Kind = "Debris",
		Category = "Crafting_L1",
		Size = {2.0, 0.3, 0.16},
		Tris = 52,
		OriginOffset = {0.0, -0.2, -0.21},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Canteen = {
		Kind = "Equippable",
		Category = "Crafting_L2",
		Size = {1.1, 1.71, 1.37},
		Tris = 418,
		OriginOffset = {0.0, -0.6215, 0.198},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Pour = {0.0, 1.4, -0.82, 1.0, 0.0, 0.0, 0.0, 0.8192, -0.5736, 0.0, 0.5736, 0.8192}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Bow = {
		Kind = "Equippable",
		Category = "Crafting_L2",
		Size = {0.28, 4.63, 0.53},
		Tris = 234,
		OriginOffset = {0.0, 0.0, 0.0625},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Nock = {0.0, 0.1, 0.18, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ArrowRest = {0.0, 0.12, -0.15, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Arrow = {
		Kind = "Projectile",
		Category = "Crafting_L2",
		Size = {0.2, 0.95, 3.05},
		Tris = 90,
		OriginOffset = {0.0, 0.0, 0.025},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Tip = {0.0, 0.0, -1.55, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Nock = {0.0, 0.0, 1.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_ArrowBundle = {
		Kind = "Pickup",
		Category = "Crafting_L2",
		Size = {0.47, 1.11, 3.05},
		Tris = 636,
		OriginOffset = {0.0425, -0.2, 0.025},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Gate = {
		Kind = "Structure",
		Category = "Crafting_L2",
		Size = {8.95, 11.04, 1.4},
		Tris = 160,
		OriginOffset = {-0.225, -5.22, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Hinge = {3.35, 0.05, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SnapLeft = {4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SnapRight = {-4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {4, 4.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.4, 9.2, 1.4}
			},
			{
				CFrame = {0.0, 7.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.6, 0.8, 1.0}
			}
		},
		Parts = {
			SM_Gate_Door = {
				Placement = {3.35, 0.05, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {3.227, -3.725, -0.08},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {-3.3, 3.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {6.6, 7.2, 0.45}
					}
				}
			}
		}
	},
	SM_Gate_Door_Damaged = {
		Kind = "MovingPart",
		Category = "Crafting_L2",
		Size = {6.7, 7.45, 0.88},
		Tris = 514,
		OriginOffset = {3.227, -3.725, -0.15},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {-3.3, 3.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {6.6, 7.2, 0.45}
			}
		},
		Parts = {

		}
	},
	SM_Spikes = {
		Kind = "Structure",
		Category = "Crafting_L2",
		Size = {8.0, 2.6, 3.55},
		Tris = 252,
		OriginOffset = {0.0, -1.3, 0.3255},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			HurtZone = {0.0, 1.3, -0.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.3, -0.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.2, 2.6, 3.0}
			}
		},
		Parts = {

		}
	},
	SM_Spikes_Damaged = {
		Kind = "Structure",
		Category = "Crafting_L2",
		Size = {8.0, 2.6, 3.55},
		Tris = 292,
		OriginOffset = {0.0, -1.3, 0.3255},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.3, -0.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.2, 2.6, 3.0}
			}
		},
		Parts = {

		}
	},
	SM_ReinforcedWall = {
		Kind = "Structure",
		Category = "Crafting_L3",
		Size = {9.08, 10.14, 1.73},
		Tris = 948,
		OriginOffset = {-0.1325, -4.9295, -0.0575},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			SnapLeft = {4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SnapRight = {-4, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.1, 4.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.9, 8.8, 1.5}
			}
		},
		Parts = {

		}
	},
	SM_ReinforcedWall_Damaged = {
		Kind = "Structure",
		Category = "Crafting_L3",
		Size = {9.13, 10.14, 1.73},
		Tris = 948,
		OriginOffset = {-0.1095, -4.929, -0.054},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.1, 4.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.9, 8.8, 1.5}
			}
		},
		Parts = {

		}
	},
	SM_Watchtower = {
		Kind = "Structure",
		Category = "Crafting_L3",
		Size = {9.05, 22.61, 9.05},
		Tris = 1100,
		OriginOffset = {0.0, -10.897, 0.0},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			TeamFlag = {0.0, 22.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Lookout = {0.0, 10.2, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {3.4, 8.7, -3.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.8, 17.4, 0.8}
			},
			{
				CFrame = {3.4, 8.7, 3.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.8, 17.4, 0.8}
			},
			{
				CFrame = {-3.4, 8.7, -3.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.8, 17.4, 0.8}
			},
			{
				CFrame = {-3.4, 8.7, 3.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.8, 17.4, 0.8}
			},
			{
				CFrame = {0.0, 10.0, 1.35, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {7.8, 0.4, 5.1}
			},
			{
				CFrame = {1.65, 10.0, -2.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {4.5, 0.4, 2.6}
			},
			{
				CFrame = {0.0, 11.9, -3.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {7.4, 3.6, 0.3}
			},
			{
				CFrame = {0.0, 11.9, 3.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {7.4, 3.6, 0.3}
			},
			{
				CFrame = {3.6, 11.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.3, 3.6, 7.4}
			},
			{
				CFrame = {-3.6, 11.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.3, 3.6, 7.4}
			},
			{
				CFrame = {0.0, 17.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {12.8, 0.8, 12.8}
			}
		},
		Parts = {

		}
	},
	SM_Sword = {
		Kind = "Equippable",
		Category = "Crafting_L3",
		Size = {0.32, 4.37, 0.95},
		Tris = 212,
		OriginOffset = {0.0, -1.565, -0.03},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Trail0 = {0.0, 0.8, -0.05, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Trail1 = {0.0, 3.6, -0.05, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Hit = {0.0, 2.6, -0.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Shield = {
		Kind = "Equippable",
		Category = "Crafting_L3",
		Size = {2.9, 2.9, 0.68},
		Tris = 730,
		OriginOffset = {0.0, 0.0, 0.29},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			Grip = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	ACC_Armor_Helmet = {
		Kind = "Accessory",
		Category = "Armor",
		Size = {1.62, 1.3, 1.67},
		Tris = 576,
		OriginOffset = {0.0, 0.45, -0.0165},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			HatAttachment = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		},
		R15Attachment = "HatAttachment"
	},
	ACC_Armor_Chest = {
		Kind = "Accessory",
		Category = "Armor",
		Size = {2.2, 1.92, 1.32},
		Tris = 428,
		OriginOffset = {0.0, 0.02, -0.3385},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			BodyFrontAttachment = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		},
		R15Attachment = "BodyFrontAttachment"
	},
	ACC_Armor_Back = {
		Kind = "Accessory",
		Category = "Armor",
		Size = {2.1, 2.05, 0.49},
		Tris = 112,
		OriginOffset = {0.0, 0.175, -0.226},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {
			BodyBackAttachment = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		},
		R15Attachment = "BodyBackAttachment"
	},
	ACC_Armor_ShoulderL = {
		Kind = "Accessory",
		Category = "Armor",
		Size = {1.58, 0.98, 1.17},
		Tris = 544,
		OriginOffset = {-0.01, 0.088, 0.025},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			LeftShoulderAttachment = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		},
		R15Attachment = "LeftShoulderAttachment"
	},
	ACC_Armor_ShoulderR = {
		Kind = "Accessory",
		Category = "Armor",
		Size = {1.58, 0.98, 1.17},
		Tris = 544,
		OriginOffset = {0.01, 0.088, 0.025},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			RightShoulderAttachment = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		},
		R15Attachment = "RightShoulderAttachment"
	},
	ACC_Armor_Belt = {
		Kind = "Accessory",
		Category = "Armor",
		Size = {2.22, 1.03, 1.34},
		Tris = 376,
		OriginOffset = {0.0, 0.3375, 0.06},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			WaistCenterAttachment = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {

		},
		R15Attachment = "WaistCenterAttachment"
	},
	SM_Pickup_Stick = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.7, 0.47, 0.52},
		Tris = 96,
		OriginOffset = {-0.0005, -0.2, 0.007},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Stone = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.41, 0.69, 0.92},
		Tris = 160,
		OriginOffset = {0.0385, -0.3465, -0.0135},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Wood = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.07, 0.93, 1.3},
		Tris = 72,
		OriginOffset = {0.0, -0.447, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Fiber = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {0.54, 0.31, 1.66},
		Tris = 174,
		OriginOffset = {0.0, -0.18, -0.024},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Rope = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.56, 0.36, 1.23},
		Tris = 606,
		OriginOffset = {0.1625, -0.166, 0.0015},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Leather = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.3, 0.49, 1.29},
		Tris = 204,
		OriginOffset = {0.0, -0.18, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Ammo = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.25, 0.81, 0.85},
		Tris = 506,
		OriginOffset = {0.0, -0.4125, 0.025},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Bandage = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {0.55, 0.77, 1.47},
		Tris = 140,
		OriginOffset = {0.0, -0.36, 0.3665},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickup_Diamond = {
		Kind = "Pickup",
		Category = "Pickups",
		Size = {1.32, 1.04, 1.32},
		Tris = 48,
		OriginOffset = {0.0, -0.57, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_CarePackage_Crate = {
		Kind = "Structure",
		Category = "Loot",
		Size = {4.45, 3.41, 4.45},
		Tris = 692,
		OriginOffset = {0.0, -1.6975, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			ItemSpawn1 = {3.8302, 0.1, -3.2139, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ItemSpawn2 = {0.0, 0.1, -5.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ItemSpawn3 = {-3.8302, 0.1, -3.2139, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ParachuteLink = {0.0, 3.8, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Smoke = {-1.6, 3.9, -1.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Prompt = {0.0, 2.4, -2.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {4.2, 3.4, 4.2}
			}
		},
		Parts = {
			SM_CarePackage_Lid = {
				Placement = {0.0, 3.4, 2.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, -0.226, 2.045},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.18, -2.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {4.2, 0.36, 4.2}
					}
				}
			}
		}
	},
	SM_Parachute_Canopy = {
		Kind = "Effect",
		Category = "Loot",
		Size = {14.0, 4.4, 14.0},
		Tris = 320,
		OriginOffset = {0.0, -14.2, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Parachute_Lines = {
		Kind = "Effect",
		Category = "Loot",
		Size = {13.89, 12.44, 13.89},
		Tris = 164,
		OriginOffset = {0.0, -5.8195, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Beacon = {
		Kind = "WorldProp",
		Category = "Loot",
		Size = {1.78, 5.12, 2.02},
		Tris = 130,
		OriginOffset = {0.274, -2.4405, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Light = {0.0, 3.45, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Smoke = {0.0, 3.9, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.6, 3.2, 1.6}
			}
		},
		Parts = {

		}
	},
	SM_LandingMarker = {
		Kind = "WorldProp",
		Category = "Loot",
		Size = {7.99, 0.33, 7.99},
		Tris = 344,
		OriginOffset = {0.0, -0.165, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_SupplyCrate_Small01 = {
		Kind = "Structure",
		Category = "Loot",
		Size = {1.86, 1.52, 1.9},
		Tris = 80,
		OriginOffset = {0.0, -0.75, 0.0275},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Prompt = {0.0, 1.5, -1.7, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Contents = {0.0, 0.75, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.75, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.8, 1.5, 1.8}
			}
		},
		Parts = {
			SM_SupplyCrate_Small01_Lid = {
				Placement = {0.0, 1.5, 0.9, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, -0.125, 0.9},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.1, -0.9, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {1.9, 0.2, 1.9}
					}
				}
			}
		}
	},
	SM_SupplyCrate_Small02 = {
		Kind = "Structure",
		Category = "Loot",
		Size = {3.26, 1.12, 1.51},
		Tris = 80,
		OriginOffset = {0.0, -0.55, 0.0275},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Prompt = {0.0, 1.1, -1.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Contents = {0.0, 0.55, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.55, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {3.2, 1.1, 1.4}
			}
		},
		Parts = {
			SM_SupplyCrate_Small02_Lid = {
				Placement = {0.0, 1.1, 0.7, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, -0.125, 0.7},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.1, -0.7, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {3.3, 0.2, 1.5}
					}
				}
			}
		}
	},
	SM_SupplyCrate_Small03 = {
		Kind = "Structure",
		Category = "Loot",
		Size = {3.73, 1.31, 3.36},
		Tris = 160,
		OriginOffset = {0.4, -0.655, -0.3},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Prompt = {0.0, 1.3, -1.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Contents = {0.0, 0.65, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.65, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.2, 1.3, 1.6}
			}
		},
		Parts = {
			SM_SupplyCrate_Small03_Lid = {
				Placement = {0.0, 1.3, 0.8, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, -0.125, 0.8},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.1, -0.8, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {2.3, 0.2, 1.7}
					}
				}
			}
		}
	},
	SM_Bandage_Held = {
		Kind = "Equippable",
		Category = "Loot",
		Size = {0.45, 1.46, 0.73},
		Tris = 140,
		OriginOffset = {0.0, 0.319, 0.0685},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Ammo_Pistol = {
		Kind = "Pickup",
		Category = "Loot",
		Size = {0.9, 0.75, 0.62},
		Tris = 176,
		OriginOffset = {0.0, -0.3675, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Ammo_Shotgun = {
		Kind = "Pickup",
		Category = "Loot",
		Size = {1.1, 0.95, 0.7},
		Tris = 268,
		OriginOffset = {0.0, -0.475, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Ammo_Rifle = {
		Kind = "Pickup",
		Category = "Loot",
		Size = {1.3, 0.96, 0.6},
		Tris = 206,
		OriginOffset = {0.0, -0.4825, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pistol = {
		Kind = "Equippable",
		Category = "Firearms",
		Size = {0.28, 1.05, 1.41},
		Tris = 186,
		OriginOffset = {0.0, 0.096, 0.3035},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Grip = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Muzzle = {0.0, 0.47, -1.08, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ShellEject = {0.2, 0.52, -0.1, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, -1.0, 0.0, 0.0}
		},
		CollisionBoxes = {},
		Parts = {
			SM_Pistol_Slide = {
				Placement = {0.0, 0.47, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {-0.0025, -0.0275, 0.335},
				Attachments = {

				},
				CollisionBoxes = {}
			}
		}
	},
	SM_Shotgun = {
		Kind = "Equippable",
		Category = "Firearms",
		Size = {0.33, 1.08, 5.67},
		Tris = 398,
		OriginOffset = {0.0, -0.049, 0.763},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Grip = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Muzzle = {0.0, 0.42, -3.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ShellEject = {0.2, 0.45, -0.45, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, -1.0, 0.0, 0.0},
			SecondHand = {0.0, 0.22, -1.5, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {
			SM_Shotgun_Pump = {
				Placement = {0.0, 0.22, -1.9, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, 0.0, -0.131},
				Attachments = {

				},
				CollisionBoxes = {}
			}
		}
	},
	SM_Rifle = {
		Kind = "Equippable",
		Category = "Firearms",
		Size = {0.34, 1.24, 5.69},
		Tris = 582,
		OriginOffset = {0.0, -0.059, 0.556},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Grip = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Muzzle = {0.0, 0.52, -3.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			ShellEject = {0.2, 0.6, 0.05, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, -1.0, 0.0, 0.0},
			SecondHand = {0.0, 0.2, -1.4, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {},
		Parts = {
			SM_Rifle_Bolt = {
				Placement = {0.0, 0.52, 0.35, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {-0.173, 0.115, 0.0},
				Attachments = {

				},
				CollisionBoxes = {}
			}
		}
	},
	SK_Wolf = {
		Kind = "Rig",
		Category = "Wildlife",
		Size = {1.64, 4.05, 6.51},
		Tris = 1986,
		OriginOffset = {0.0, 0.0, 0.0},
		CollisionFidelity = "Use the hitbox parts (CanCollide off on the skinned mesh).",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 2.35, 0.25, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.4, 1.7, 4.2},
				Name = "Body"
			},
			{
				CFrame = {0.0, 3.35, -2.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.9, 0.95, 1.5},
				Name = "Head"
			}
		},
		Parts = {

		},
		Animations = {
			Idle = {
				Frames = 60,
				Loop = true
			},
			Walk = {
				Frames = 36,
				Loop = true
			},
			Run = {
				Frames = 20,
				Loop = true
			},
			Alert = {
				Frames = 30,
				Loop = false
			},
			Attack = {
				Frames = 26,
				Loop = false
			},
			Hit = {
				Frames = 16,
				Loop = false
			},
			Death = {
				Frames = 46,
				Loop = false
			},
			Howl = {
				Frames = 70,
				Loop = false
			}
		},
		MovementCollider = {
			CFrame = {0.0, 1.85, 0.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Size = {1.5, 3.7, 6.4}
		}
	},
	SK_Bear = {
		Kind = "Rig",
		Category = "Wildlife",
		Size = {3.06, 4.72, 7.87},
		Tris = 1980,
		OriginOffset = {0.0, 0.0, 0.0},
		CollisionFidelity = "Use the hitbox parts (CanCollide off on the skinned mesh).",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 3.1, 0.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.9, 2.9, 5.6},
				Name = "Body"
			},
			{
				CFrame = {0.0, 3.6, -3.6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.6, 1.6, 2.0},
				Name = "Head"
			}
		},
		Parts = {

		},
		Animations = {
			Idle = {
				Frames = 60,
				Loop = true
			},
			Walk = {
				Frames = 36,
				Loop = true
			},
			Run = {
				Frames = 20,
				Loop = true
			},
			Alert = {
				Frames = 30,
				Loop = false
			},
			Hit = {
				Frames = 16,
				Loop = false
			},
			Death = {
				Frames = 46,
				Loop = false
			},
			Attack = {
				Frames = 30,
				Loop = false
			},
			RearUp = {
				Frames = 72,
				Loop = false
			}
		},
		MovementCollider = {
			CFrame = {0.0, 2.6, -0.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Size = {3.0, 5.2, 9.0}
		}
	},
	SK_Bat = {
		Kind = "Rig",
		Category = "Wildlife",
		Size = {5.2, 0.72, 1.91},
		Tris = 1004,
		OriginOffset = {0.0, 0.0, 0.0},
		CollisionFidelity = "Use the hitbox parts (CanCollide off on the skinned mesh).",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.2, 0.8, 1.6},
				Name = "Body"
			}
		},
		Parts = {

		},
		Animations = {
			Idle = {
				Frames = 24,
				Loop = true
			},
			Fly = {
				Frames = 24,
				Loop = true
			},
			FastFly = {
				Frames = 24,
				Loop = true
			},
			Alert = {
				Frames = 30,
				Loop = false
			},
			Attack = {
				Frames = 26,
				Loop = false
			},
			Hit = {
				Frames = 16,
				Loop = false
			},
			Death = {
				Frames = 40,
				Loop = false
			}
		},
		MovementCollider = {
			CFrame = {0.0, 0.0, 0.2, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Size = {5.4, 1.0, 1.8}
		}
	},
	SM_Lobby_GatheringArea = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {26.0, 7.3, 26.0},
		Tris = 1464,
		OriginOffset = {0.0, -3.65, 0.0},
		CollisionFidelity = "Default",
		TeamColored = false,
		Attachments = {
			Light1 = {-8.4853, 6.5, 8.4853, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Light2 = {8.4853, 6.5, 8.4853, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Light3 = {8.4853, 6.5, -8.4853, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Light4 = {-8.4853, 6.5, -8.4853, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			FirePit = {0.0, 0.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Spawn = {0.0, 0.6, -6, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {26, 0.6, 26}
			}
		},
		Parts = {

		}
	},
	SM_Lobby_ReadyStation = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {8.87, 8.66, 5.4},
		Tris = 664,
		OriginOffset = {0.0, -4.019, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Pad = {0.0, 0.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SignMount = {0.0, 6.3, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {3.5, 3.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.0, 7.4, 1.0}
			},
			{
				CFrame = {-3.5, 3.7, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {1.0, 7.4, 1.0}
			},
			{
				CFrame = {0.0, 0.17, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {5.4, 0.35, 5.4}
			}
		},
		Parts = {

		}
	},
	SM_Lobby_PartyArea = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {14.05, 8.0, 14.0},
		Tris = 532,
		OriginOffset = {0.0, -4.0, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Seat1 = {-2.9698, 2.2, 2.9698, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Seat2 = {2.9698, 2.2, 2.9698, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Seat3 = {2.9698, 2.2, -2.9698, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Seat4 = {-2.9698, 2.2, -2.9698, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			TotemTop = {0.0, 8.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 0.25, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {14, 0.5, 14}
			}
		},
		Parts = {

		}
	},
	SM_Lobby_PowerupStand = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.85, 3.95, 3.0},
		Tris = 276,
		OriginOffset = {0.0, -1.975, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Emblem = {0.0, 4.4, -0.05, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Plaque = {0.0, 0.62, -1.32, 1.0, 0.0, 0.0, 0.0, 0.866, -0.5, 0.0, 0.5, 0.866}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.6, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {2.8, 3.2, 2.8}
			}
		},
		Parts = {

		}
	},
	SM_Lobby_ShopDisplay = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {10.0, 7.37, 6.9},
		Tris = 636,
		OriginOffset = {0.0, -3.6845, 0.2525},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {
			Item1 = {3, 3.6, -2.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Item2 = {0.0, 3.6, -2.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			Item3 = {-3, 3.6, -2.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
			SignMount = {0.0, 5.2, -3.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0}
		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 1.5, -2.3, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {9.6, 3.0, 1.6}
			},
			{
				CFrame = {0.0, 2.6, 2.1, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {8.8, 5.2, 1.2}
			}
		},
		Parts = {

		}
	},
	SM_Sign_Post = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {4.0, 5.1, 0.54},
		Tris = 68,
		OriginOffset = {0.0, -2.25, -0.0015},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 2.4, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {0.4, 4.8, 0.4}
			}
		},
		Parts = {
			SM_Sign_Post_Panel = {
				Placement = {0.0, 3.6, -0.1, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, 0.0, 0.0},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {3.5, 1.8, 0.2}
					}
				}
			}
		}
	},
	SM_Sign_Hanging = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {4.5, 3.44, 0.34},
		Tris = 72,
		OriginOffset = {0.0, 1.7225, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {
			SM_Sign_Hanging_Panel = {
				Placement = {0.0, -2.2, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, 0.0, 0.0},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {4.0, 2.0, 0.2}
					}
				}
			}
		}
	},
	SM_Sign_Board = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {12.0, 9.3, 1.6},
		Tris = 112,
		OriginOffset = {0.0, -4.25, -0.1},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, 4.2, 0.1, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {10.8, 8.4, 0.8}
			}
		},
		Parts = {
			SM_Sign_Board_Panel = {
				Placement = {0.0, 5.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, 0.0, 0.0},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {9.0, 4.5, 0.2}
					}
				}
			}
		}
	},
	SM_Sign_Plaque = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {1.8, 0.94, 0.34},
		Tris = 48,
		OriginOffset = {0.0, 0.0, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {
			SM_Sign_Plaque_Panel = {
				Placement = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				OriginOffset = {0.0, 0.0, 0.0},
				Attachments = {

				},
				CollisionBoxes = {
					{
						CFrame = {0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
						Size = {1.3, 0.45, 0.2}
					}
				}
			}
		}
	},
	SM_Emblem_Trailblazer = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.64, 2.64, 0.47},
		Tris = 468,
		OriginOffset = {0.0, 0.0, -0.045},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Emblem_Scavenger = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.64, 2.64, 0.49},
		Tris = 604,
		OriginOffset = {0.0, 0.0, -0.035},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Emblem_Hunter = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.64, 2.64, 0.46},
		Tris = 600,
		OriginOffset = {0.0, 0.0, -0.05},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Emblem_Climber = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.64, 2.64, 0.49},
		Tris = 602,
		OriginOffset = {0.0, 0.0, -0.0345},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Emblem_Craftsman = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.64, 2.64, 0.48},
		Tris = 440,
		OriginOffset = {0.0, 0.0, -0.04},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Emblem_Sharpshooter = {
		Kind = "Lobby",
		Category = "Lobby",
		Size = {2.64, 2.64, 0.58},
		Tris = 782,
		OriginOffset = {0.0, 0.0, 0.01},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Cliff_Face01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {24.8, 26.38, 9.71},
		Tris = 1040,
		OriginOffset = {0.0405, -12.212, 0.2555},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Cliff_Face02 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {24.62, 23.56, 9.66},
		Tris = 644,
		OriginOffset = {0.188, -11.0735, 0.02},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_CaveEntrance = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {20.87, 15.4, 9.75},
		Tris = 972,
		OriginOffset = {-0.16, -4.2015, 0.568},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_CaveTunnel_Segment = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {14.75, 12.95, 12.4},
		Tris = 752,
		OriginOffset = {-0.1465, -5.6865, 0.368},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_CaveChamber_End = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {19.37, 15.88, 20.19},
		Tris = 920,
		OriginOffset = {0.542, -6.7265, -3.894},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Riverbank_Straight = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {16.0, 2.08, 10.06},
		Tris = 728,
		OriginOffset = {0.0, 0.36, 0.0285},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Riverbank_Bend = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {13.77, 2.08, 12.64},
		Tris = 728,
		OriginOffset = {2.5485, 0.36, -1.318},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Ground_Forest01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {32.0, 2.54, 32.0},
		Tris = 1152,
		OriginOffset = {0.0, 0.7305, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, -1, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {32, 2, 32}
			}
		},
		Parts = {

		}
	},
	SM_Ground_Clearing01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {32.0, 2.74, 32.0},
		Tris = 1392,
		OriginOffset = {0.0, 0.6305, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {
			{
				CFrame = {0.0, -1, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0},
				Size = {32, 2, 32}
			}
		},
		Parts = {

		}
	},
	SM_Trail_Segment01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {4.96, 0.66, 12.02},
		Tris = 144,
		OriginOffset = {0.08, -0.2715, -0.002},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Roots01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {4.97, 0.57, 4.82},
		Tris = 130,
		OriginOffset = {0.028, -0.264, -0.2065},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Roots02 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {4.86, 0.93, 2.72},
		Tris = 108,
		OriginOffset = {-0.0055, -0.4095, -0.0065},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Flowers01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {2.53, 1.04, 2.31},
		Tris = 308,
		OriginOffset = {-0.021, -0.396, -0.021},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Flowers02 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {2.44, 1.03, 2.37},
		Tris = 308,
		OriginOffset = {0.0905, -0.388, 0.115},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Sapling01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {2.46, 5.07, 2.41},
		Tris = 266,
		OriginOffset = {0.114, -2.3315, -0.068},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Tree_Spruce01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {12.21, 20.41, 12.03},
		Tris = 166,
		OriginOffset = {0.0, -9.797, -0.187},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Tree_Spruce02 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {14.42, 24.45, 14.2},
		Tris = 198,
		OriginOffset = {0.0, -11.8205, -0.2205},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Tree_Aspen01 = {
		Kind = "WorldProp",
		Category = "SW_Landscape",
		Size = {7.67, 19.22, 7.54},
		Tris = 598,
		OriginOffset = {-0.1635, -9.304, 0.1745},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_ScrapPile01 = {
		Kind = "Harvestable",
		Category = "SW_Landscape",
		Size = {4.33, 2.09, 3.75},
		Tris = 220,
		OriginOffset = {0.0, -0.706, 0.0055},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_OreDeposit_Coal = {
		Kind = "Harvestable",
		Category = "SW_Landscape",
		Size = {5.23, 3.59, 4.49},
		Tris = 200,
		OriginOffset = {0.1045, -1.19, 0.2055},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_OreDeposit_Iron = {
		Kind = "Harvestable",
		Category = "SW_Landscape",
		Size = {5.37, 3.26, 4.56},
		Tris = 200,
		OriginOffset = {-0.021, -1.1585, 0.0205},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_Campsite = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {18.46, 3.71, 15.03},
		Tris = 436,
		OriginOffset = {0.07, -1.746, 1.5705},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_Shed = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {9.0, 7.83, 6.96},
		Tris = 724,
		OriginOffset = {0.0, -3.8145, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_HuntingBlind = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {6.4, 8.6, 6.9},
		Tris = 256,
		OriginOffset = {0.0, -4.3, -0.25},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_BrokenVehicle = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {15.11, 5.35, 9.42},
		Tris = 368,
		OriginOffset = {-1.066, -2.6765, 2.0705},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_SmallCabin = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {10.87, 11.6, 10.9},
		Tris = 1040,
		OriginOffset = {0.0, -5.7, -0.95},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_Cabin = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {14.87, 12.84, 13.4},
		Tris = 1204,
		OriginOffset = {0.0, -6.319, -1.2},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_RangerStation = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {15.56, 12.84, 22.1},
		Tris = 1428,
		OriginOffset = {-0.3485, -6.319, 2.35},
		CollisionFidelity = "Box",
		TeamColored = true,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_LoggingCamp = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {19.11, 9.42, 24.0},
		Tris = 960,
		OriginOffset = {0.8795, -4.6095, 5.5},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_AbandonedHouse = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {16.48, 13.98, 17.62},
		Tris = 1238,
		OriginOffset = {-0.191, -6.889, 2.31},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_MineEntrance = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {15.71, 8.47, 20.56},
		Tris = 596,
		OriginOffset = {0.138, -3.4155, -1.2195},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_Bunker = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {14.6, 8.7, 14.92},
		Tris = 912,
		OriginOffset = {0.0, -4.25, -1.1605},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_Outpost = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {26.56, 9.36, 20.6},
		Tris = 722,
		OriginOffset = {0.0, -4.518, 3.25},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_IndustrialSite = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {34.93, 10.6, 22.5},
		Tris = 312,
		OriginOffset = {-0.4655, -5.3, -2.25},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_POI_LargeMine = {
		Kind = "Structure",
		Category = "SW_POI",
		Size = {19.35, 14.81, 20.95},
		Tris = 776,
		OriginOffset = {-1.325, -6.174, -1.027},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Chest_Common = {
		Kind = "Structure",
		Category = "SW_Loot",
		Size = {3.4, 2.4, 2.47},
		Tris = 144,
		OriginOffset = {0.0, -1.2, 0.0625},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Chest_Uncommon = {
		Kind = "Structure",
		Category = "SW_Loot",
		Size = {3.4, 2.4, 2.47},
		Tris = 144,
		OriginOffset = {0.0, -1.2, 0.0625},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Chest_Rare = {
		Kind = "Structure",
		Category = "SW_Loot",
		Size = {3.4, 2.4, 2.53},
		Tris = 156,
		OriginOffset = {0.0, -1.2, 0.09},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Chest_VeryRare = {
		Kind = "Structure",
		Category = "SW_Loot",
		Size = {3.4, 2.4, 2.53},
		Tris = 156,
		OriginOffset = {0.0, -1.2, 0.09},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickaxe_Stone = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {0.47, 3.61, 2.2},
		Tris = 332,
		OriginOffset = {0.0, -1.103, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Pickaxe_Iron = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {0.31, 3.61, 2.62},
		Tris = 180,
		OriginOffset = {0.0, -1.103, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Axe_Iron = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {0.31, 3.61, 1.58},
		Tris = 136,
		OriginOffset = {0.0, -1.103, 0.31},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Crowbar = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {0.14, 3.5, 0.88},
		Tris = 60,
		OriginOffset = {0.0, -0.634, 0.166},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Sledgehammer = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {0.6, 4.2, 1.5},
		Tris = 156,
		OriginOffset = {0.0, -1.399, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_HuntingBow = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {0.3, 4.84, 0.77},
		Tris = 96,
		OriginOffset = {0.0, 0.0, -0.0855},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Crossbow = {
		Kind = "Equippable",
		Category = "SW_Tools",
		Size = {3.21, 0.95, 3.05},
		Tris = 126,
		OriginOffset = {0.0, -0.075, 0.9235},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_ReinforcedChest = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {6.2, 4.3, 4.3},
		Tris = 124,
		OriginOffset = {0.0, -2.15, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_MetalLocker = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {4.0, 7.0, 3.2},
		Tris = 92,
		OriginOffset = {0.0, -3.5, 0.1},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_SurvivalSafe = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {4.5, 5.0, 4.8},
		Tris = 100,
		OriginOffset = {0.0, -2.5, 0.15},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_ScrapWall = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {10.46, 10.4, 1.35},
		Tris = 108,
		OriginOffset = {-0.0815, -5.2, 0.325},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_MetalWall = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {10.8, 11.0, 2.6},
		Tris = 288,
		OriginOffset = {0.0, -5.5, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_WoodFloor = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {10.0, 1.0, 10.02},
		Tris = 376,
		OriginOffset = {0.0, -0.5, -0.01},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_BearTrap = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {2.56, 0.55, 1.76},
		Tris = 360,
		OriginOffset = {0.0, -0.275, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Snare = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {3.14, 3.25, 2.46},
		Tris = 138,
		OriginOffset = {0.3095, -1.6035, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_TripwireAlarm = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {7.91, 1.4, 0.53},
		Tris = 96,
		OriginOffset = {0.003, -0.7, -0.115},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Workbench_Level04 = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {12.1, 7.7, 4.0},
		Tris = 160,
		OriginOffset = {2.05, -3.85, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	},
	SM_Workbench_Level05 = {
		Kind = "Structure",
		Category = "SW_Base",
		Size = {12.15, 7.7, 4.1},
		Tris = 208,
		OriginOffset = {2.025, -3.85, 0.0},
		CollisionFidelity = "Box",
		TeamColored = false,
		Attachments = {

		},
		CollisionBoxes = {},
		Parts = {

		}
	}
}
