--[[
	SURVIVAL HOUR: ONE-PASTE STUDIO SETUP  (run in View > Command Bar, edit mode, NOT while playing)

	Before running:
	  1. Home > Import 3D: select every .fbx in Export/Meshes/* (all folders) and Export/Rigs/*.
	     Settings: World Forward = Front, World Up = Top, Scale Unit = Stud.
	  2. (Optional, for full-quality textures) upload the 8 PNGs in Textures/ with the Asset Manager
	     and paste their ids into TEXTURES below. Leave them "" to keep the preview texture that
	     each file already has embedded.
	  3. Paste this whole file into the Command Bar and press Enter.
	  Safe to run again: assets already in ServerStorage.SurvivalHour are skipped, so if some files
	  were missing you can import just those and re-run.

	Result:
	  ServerStorage > SurvivalHour > <Category> > ready-made Models, Tools (Crafting/Firearms/Loot) and
	  Accessories (Armor). Rigged animals get an AnimationController + Animator and hitboxes.
	  A showcase copy of everything is laid out in Workspace > SurvivalHour_Showcase (set SHOWCASE =
	  false to skip). Ctrl+Z undoes the whole run.

	GENERATED by blender/make_docs.py. Written without access to Roblox Studio, so it has not been
	run in Studio yet. If something errors, copy the Output window text back to Claude.
]]

local TEXTURES = {
	Color = { Neutral = "", Red = "", Blue = "", Yellow = "", Purple = "" }, -- e.g. "rbxassetid://123"
	Normal = "",
	Roughness = "",
	Metalness = "",
}
local SHOWCASE = true

local DATA = --@@DATA@@

---------------------------------------------------------------------------------------------------
local ServerStorage = game:GetService("ServerStorage")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local History = game:GetService("ChangeHistoryService")

local DECOR_PREFIXES = { "SM_Grass", "SM_Fern", "SM_Bush", "SM_FiberPlant", "SM_LeafLitter", "SM_MossPatch",
	"SM_Branch", "SM_Sticks", "SM_Mushrooms", "SM_Pinecones", "SM_Clearing", "SM_Camp_Bedroll",
	"SM_LandingMarker", "SM_Debris" }

local report = { made = 0, missing = {}, warnings = {} }
local function warnf(...)
	local msg = string.format(...)
	table.insert(report.warnings, msg)
	warn("[SurvivalHour] " .. msg)
end

local function cf(t)
	return CFrame.new(table.unpack(t))
end
local function originOf(e)
	local o = e.OriginOffset or { 0, 0, 0 }
	return CFrame.new(o[1], o[2], o[3])
end
local function isDecor(name)
	for _, p in DECOR_PREFIXES do
		if string.sub(name, 1, #p) == p then
			return true
		end
	end
	return false
end
local function folder(parent, name)
	local f = parent:FindFirstChild(name)
	if not f then
		f = Instance.new("Folder")
		f.Name = name
		f.Parent = parent
	end
	return f
end

History:SetWaypoint("Before Survival Hour setup")

-- 1. Team texture templates -------------------------------------------------------------------
local templates = nil
if TEXTURES.Color.Neutral ~= "" then
	local atlas = folder(ReplicatedStorage, "SurvivalHourAtlas")
	templates = {}
	for team, id in TEXTURES.Color do
		if id ~= "" then
			local sa = atlas:FindFirstChild(team) or Instance.new("SurfaceAppearance")
			sa.Name = team
			sa.ColorMap = id
			sa.NormalMap = TEXTURES.Normal
			sa.RoughnessMap = TEXTURES.Roughness
			sa.MetalnessMap = TEXTURES.Metalness
			sa.Parent = atlas
			templates[team] = sa
		end
	end
end

-- 2. Find imported meshes ---------------------------------------------------------------------
local partOwner = {} -- part name -> {owner, info}
for name, e in DATA do
	for pname, info in e.Parts do
		partOwner[pname] = { owner = name, info = info }
	end
end

local root = folder(ServerStorage, "SurvivalHour")

-- Names can come back from the importer as "SM_Sword.001", "SM_Sword (1)" or "Handle" inside a
-- Tool/Accessory/Model named after the file, so normalise and also look at ancestors.
local function clean(n)
	n = string.gsub(n, "%.%d+$", "")
	n = string.gsub(n, "%s*%(%d+%)$", "")
	return n
end
local function known(n)
	return DATA[n] or partOwner[n]
end
local function alreadyBuilt(name)
	local e = DATA[name]
	if not e then
		return false
	end
	local cat = root:FindFirstChild(e.Category)
	if not cat then
		return false
	end
	local short = string.gsub(string.gsub(name, "^SM_", ""), "^ACC_", "")
	return cat:FindFirstChild(name) ~= nil or cat:FindFirstChild(short) ~= nil
end

local found = {}
local strayAtt = {}
local showcase = workspace:FindFirstChild("SurvivalHour_Showcase")
local searchRoots = { workspace, ReplicatedStorage, ServerStorage, game:GetService("StarterPack"),
	game:GetService("Lighting") }
for _, sr in searchRoots do
	for _, d in sr:GetDescendants() do
		if d:IsA("MeshPart") and not (showcase and d:IsDescendantOf(showcase)) and not d:IsDescendantOf(root) then
			if string.sub(d.Name, -4) == "_Att" then
				table.insert(strayAtt, d) -- importer left an attachment marker as a mesh
			else
				local key = clean(d.Name)
				local node = d.Parent
				while not known(key) and node and node ~= game do
					key = clean(node.Name)
					node = node.Parent
				end
				if known(key) and not found[key] and not alreadyBuilt(key) then
					found[key] = d
				end
			end
		end
	end
end
for _, s in strayAtt do
	s:Destroy() -- rebuilt from DATA below
end

local function prepareMesh(mesh, e, anchored)
	mesh.Anchored = anchored
	for _, c in mesh:GetChildren() do
		if c:IsA("Attachment") and string.sub(c.Name, -4) == "_Att" then
			c.Name = string.sub(c.Name, 1, -5)
		end
	end
	local origin = originOf(e)
	for aname, t in e.Attachments do
		if not mesh:FindFirstChild(aname) then
			local a = Instance.new("Attachment")
			a.Name = aname
			a.CFrame = origin * cf(t)
			a.Parent = mesh
		end
	end
	mesh.PivotOffset = origin
	if templates then
		local old = mesh:FindFirstChildOfClass("SurfaceAppearance")
		if old then
			old:Destroy()
		end
		templates.Neutral:Clone().Parent = mesh
	end
	if e.TeamColored then
		mesh:SetAttribute("TeamColored", true) -- swap SurfaceAppearance per team at runtime
	end
end

local function addCollision(parent, mesh, e)
	local originWorld = mesh.CFrame * originOf(e)
	for i, box in e.CollisionBoxes do
		local p = Instance.new("Part")
		p.Name = "Collision" .. i
		p.Transparency = 1
		p.CastShadow = false
		p.Anchored = true
		p.Size = Vector3.new(box.Size[1], box.Size[2], box.Size[3])
		p.CFrame = originWorld * cf(box.CFrame)
		p.Parent = parent
	end
	if #e.CollisionBoxes > 0 then
		mesh.CanCollide = false
	end
end

local function setFidelity(mesh, e)
	local ok = pcall(function()
		mesh.CollisionFidelity = Enum.CollisionFidelity[e.CollisionFidelity] or Enum.CollisionFidelity.Box
	end)
	if not ok then
		mesh.CollisionFidelity = Enum.CollisionFidelity.Box
	end
end

local function placeParts(container, mesh, e, weld)
	local originWorld = mesh.CFrame * originOf(e)
	for pname, info in e.Parts do
		local p = found[pname]
		if p then
			prepareMesh(p, info, not weld)
			p.CFrame = originWorld * cf(info.Placement) * originOf(info):Inverse()
			p.Parent = container
			if weld then
				p.CanCollide = false
				p.Massless = true
				local w = Instance.new("WeldConstraint")
				w.Part0 = mesh
				w.Part1 = p
				w.Parent = p
			else
				addCollision(container, p, info)
			end
		else
			table.insert(report.missing, pname)
		end
	end
end

-- 3. Build each asset -------------------------------------------------------------------------
for name, e in DATA do
	local mesh = found[name]
	if not mesh then
		if alreadyBuilt(name) then
			report.skipped = (report.skipped or 0) + 1
		else
			table.insert(report.missing, name)
		end
		continue
	end
	local ok, err = pcall(function()
		local cat = folder(root, e.Category)
		local kind = e.Kind
		if kind == "Rig" then
			-- nearest ancestor Model that holds this skinned mesh and its bones, and nothing else big
			local model = nil
			local node = mesh.Parent
			while node and node ~= workspace do
				if node:IsA("Model") then
					local meshes = 0
					for _, d in node:GetDescendants() do
						if d:IsA("MeshPart") then
							meshes += 1
						end
					end
					if meshes == 1 and node:FindFirstChildWhichIsA("Bone", true) then
						model = node
						break
					end
				end
				node = node.Parent
			end
			if not model then
				warnf("%s: rig container not found; wrapping the mesh in a new Model (move its bones in manually)", name)
				model = Instance.new("Model")
				model.Name = name
				mesh.Parent = model
			end
			model.Name = name
			local ctrl = model:FindFirstChildOfClass("AnimationController") or model:FindFirstChildOfClass("Humanoid")
			if not ctrl then
				ctrl = Instance.new("AnimationController")
				ctrl.Parent = model
			end
			if not ctrl:FindFirstChildOfClass("Animator") then
				Instance.new("Animator").Parent = ctrl
			end
			mesh.CanCollide = false
			local rootBone = model:FindFirstChild("Root", true)
			local rootCF = rootBone and rootBone:IsA("Bone") and rootBone.WorldCFrame or mesh.CFrame
			if not (rootBone and rootBone:IsA("Bone")) then
				warnf("%s: no Root bone found; hitboxes placed at the mesh centre", name)
			end
			for _, box in e.CollisionBoxes do
				local hb = Instance.new("Part")
				hb.Name = "Hitbox_" .. (box.Name or "Body")
				hb.Transparency = 1
				hb.CanCollide = false
				hb.Massless = true
				hb.Anchored = false
				hb.Size = Vector3.new(box.Size[1], box.Size[2], box.Size[3])
				hb.CFrame = rootCF * cf(box.CFrame)
				local boneName = box.Name == "Head" and "Head" or (model:FindFirstChild("Hips", true) and "Hips" or "Body")
				local bone = model:FindFirstChild(boneName, true)
				if bone and bone:IsA("Bone") then
					local a = Instance.new("Attachment")
					a.CFrame = hb.CFrame:ToObjectSpace(bone.WorldCFrame)
					a.Parent = hb
					local rc = Instance.new("RigidConstraint")
					rc.Attachment0 = bone
					rc.Attachment1 = a
					rc.Parent = hb
				end
				hb.Parent = model
			end
			model.Parent = cat
		elseif kind == "Equippable" then
			prepareMesh(mesh, e, false)
			local tool = Instance.new("Tool")
			tool.Name = string.gsub(name, "^SM_", "")
			tool.Grip = originOf(e)
			mesh.Name = "Handle"
			mesh.CanCollide = false
			mesh.Parent = tool
			placeParts(tool, mesh, e, true)
			tool.Parent = cat
		elseif kind == "Accessory" then
			prepareMesh(mesh, e, false)
			local acc = Instance.new("Accessory")
			acc.Name = string.gsub(name, "^ACC_", "")
			mesh.Name = "Handle"
			mesh.CanCollide = false
			mesh.Massless = true
			local att = mesh:FindFirstChild(e.R15Attachment)
			if att then
				att.CFrame = originOf(e)
			end
			mesh.Parent = acc
			acc.Parent = cat
		else
			local model = Instance.new("Model")
			model.Name = name
			prepareMesh(mesh, e, kind ~= "Debris")
			mesh.Parent = model
			model.PrimaryPart = mesh
			if kind == "Effect" or kind == "Projectile" then
				mesh.CanCollide = false
				mesh.CanQuery = false
				mesh.CanTouch = false
				mesh.CastShadow = false
				if string.find(name, "Flames") then
					mesh.Material = Enum.Material.Neon
					mesh.Color = Color3.fromRGB(255, 140, 50)
				elseif string.find(name, "Water") then
					mesh.Transparency = 0.35
					mesh.Material = Enum.Material.Glass
				end
			elseif isDecor(name) then
				mesh.CanCollide = false
				mesh.CanTouch = false
			elseif #e.CollisionBoxes > 0 then
				addCollision(model, mesh, e)
			else
				setFidelity(mesh, e)
			end
			placeParts(model, mesh, e, false)
			model.WorldPivot = mesh.CFrame * originOf(e)
			model.Parent = cat
		end
		report.made += 1
	end)
	if not ok then
		warnf("%s: %s", name, tostring(err))
	end
end

-- remove now-empty import containers left in Workspace
for _, d in workspace:GetChildren() do
	if d:IsA("Model") and #d:GetDescendants() == 0 then
		d:Destroy()
	end
end

-- 4. Showcase: a copy of everything laid out in rows by category -------------------------------
if SHOWCASE then
	local old = workspace:FindFirstChild("SurvivalHour_Showcase")
	if old then
		old:Destroy()
	end
	local show = Instance.new("Model")
	show.Name = "SurvivalHour_Showcase"
	local z = 0
	local order = { "Reference", "Forest", "Stream", "Camp", "Crafting_L1", "Crafting_L2", "Crafting_L3",
		"Armor", "Pickups", "Loot", "Firearms", "Wildlife", "Lobby" }
	for _, catName in order do
		local cat = root:FindFirstChild(catName)
		if cat then
			local x, depth = 0, 0
			local items = cat:GetChildren()
			table.sort(items, function(a, b)
				return a.Name < b.Name
			end)
			for _, item in items do
				local c = item:Clone()
				local size
				if c:IsA("Model") then
					size = c:GetExtentsSize()
				else
					local h = c:FindFirstChild("Handle")
					size = h and h.Size or Vector3.new(2, 2, 2)
				end
				local pos = CFrame.new(x + size.X / 2, 0, z)
				if c:IsA("Model") then
					c:PivotTo(pos)
				elseif c:IsA("Tool") or c:IsA("Accessory") then
					local h = c:FindFirstChild("Handle")
					if h then
						-- move every part together (welds don't act in edit mode)
						local delta = (pos * CFrame.new(0, size.Y / 2 + 0.5, 0)) * h.CFrame:Inverse()
						for _, p in c:GetDescendants() do
							if p:IsA("BasePart") then
								p.Anchored = true
								p.CFrame = delta * p.CFrame
							end
						end
					end
				end
				c.Parent = show
				x += size.X + 4
				depth = math.max(depth, size.Z)
			end
			z += depth + 12
		end
	end
	show.Parent = workspace
end

History:SetWaypoint("Survival Hour setup")

-- 5. Report ----------------------------------------------------------------------------------
print(string.format("[SurvivalHour] Set up %d assets into ServerStorage.SurvivalHour (%d already done earlier).",
	report.made, report.skipped or 0))
if #report.missing > 0 then
	table.sort(report.missing)
	print("[SurvivalHour] Not found anywhere (not imported?): " .. table.concat(report.missing, ", "))
	print("[SurvivalHour] Import just those files and run this script again; finished assets are skipped.")
end
if #report.warnings > 0 then
	print(string.format("[SurvivalHour] %d warning(s) above.", #report.warnings))
end
