"""Generate src/shared/AssetIds.luau: uploaded Roblox model ids joined with the
pack catalog (size, origin offset, kind, category, sub-parts), so the server can
load the meshes with InsertService and build the mesh library at runtime.

    python3 tools/gen_asset_ids.py
Inputs: Roblox/uploaded_model_ids.json (upload report), Roblox/catalog.json
"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def num(v):
    s = f"{v:.4f}".rstrip("0").rstrip(".")
    return s if s not in ("-0", "") else "0"


def vec(v):
    return "{" + ", ".join(num(x) for x in v) + "}"


def main():
    ids_doc = json.load(open(os.path.join(ROOT, "Roblox", "uploaded_model_ids.json")))
    ids = {key.split("/", 1)[1]: int(v) for key, v in ids_doc["models"].items()}
    catalog = {r["name"]: r for r in json.load(open(os.path.join(ROOT, "Roblox", "catalog.json")))
               if "size_studs_roblox_XYZ" in r}
    lines = []
    missing = []
    for name in sorted(ids):
        r = catalog.get(name)
        if not r:
            continue  # sub-parts only appear inside their parent record
        parts = []
        for p in r.get("parts", []):
            if p["name"] in ids:
                parts.append("{ Name = %s, Id = %d, Size = %s, Offset = %s, Place = %s }" % (
                    json.dumps(p["name"]), ids[p["name"]], vec(p["size_studs_roblox_XYZ"]),
                    vec(p["origin_offset"]), vec(p["placement_cframe"])))
            else:
                missing.append(p["name"])
        lines.append("\t[%s] = { Id = %d, Kind = %s, Category = %s, Size = %s, Offset = %s, Parts = { %s } }," % (
            json.dumps(name), ids[name], json.dumps(r["kind"]), json.dumps(r["category"]),
            vec(r["size_studs_roblox_XYZ"]), vec(r["origin_offset"]), ", ".join(parts)))
    owner = ids_doc.get("owner", {})
    out = os.path.join(ROOT, "src", "shared", "AssetIds.luau")
    with open(out, "w") as f:
        f.write("--!strict\n")
        f.write("-- GENERATED by tools/gen_asset_ids.py from Roblox/uploaded_model_ids.json + Roblox/catalog.json.\n")
        f.write("-- Uploaded mesh models (owner: %s %s) the server loads with InsertService\n" % (owner.get("name", "?"), owner.get("id", "?")))
        f.write("-- (AssetLoaderService). Size / Offset are the authored size and pivot offset\n")
        f.write("-- from the pack catalog, in studs (Roblox axes).\n\n")
        f.write("export type Part = { Name: string, Id: number, Size: { number }, Offset: { number }, Place: { number } }\n")
        f.write("export type Entry = { Id: number, Kind: string, Category: string, Size: { number }, Offset: { number }, Parts: { Part } }\n\n")
        f.write("local AssetIds: { [string]: Entry } = {\n")
        f.write("\n".join(lines))
        f.write("\n}\n\nreturn AssetIds\n")
    print(f"{len(lines)} assets -> {out}")
    if missing:
        print("sub-parts without an uploaded id:", ", ".join(missing))


if __name__ == "__main__":
    main()
