#!/usr/bin/env python3
"""Egg Farm headless integration runner (offline Roblox MOCK, not Roblox).

Builds one Luau chunk per scenario: the mock (tools/headless/mock/*.luau), the DataModel tree
from `rojo sourcemap test.project.json` (every script's source embedded), the shared scenario
helpers (scenarios/_lib.luau) and the scenario itself, then runs it with the Luau CLI.

    python3 tools/headless/run.py                 # every scenario
    python3 tools/headless/run.py fresh_player_tutorial menus_route
    python3 tools/headless/run.py --list
    python3 tools/headless/run.py perf_large_population --set SECONDS=60 --set PROFILE=1

Scenario output lines: PASS/FAIL/NOTE. Blocks between `@@FILE <path>` and `@@END` are written
to that path (relative to egg-farm/). Logs go to tools/headless/out/<scenario>.log.
Exit code 1 if any scenario has a FAIL, a game runtime error, or crashes.
"""
import json
import os
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
TOOLS = os.environ.get("EF_TOOLS") or os.environ.get("SH_TOOLS") or "/tmp/sh-tools"
LUAU = os.path.join(TOOLS, "luau", "luau")
ROJO = os.path.join(TOOLS, "rojo", "rojo")
OUT = os.path.join(HERE, "out")
PROJECT = "test.project.json"

COLOR_PROPS = {"Ambient", "OutdoorAmbient", "FogColor", "ColorShift_Top", "ColorShift_Bottom"}
ENUM_PROPS = {"Technology": "Technology"}


def long_string(s: str) -> str:
    n = 1
    while ("]" + "=" * n + "]") in s:
        n += 1
    eq = "=" * n
    # a leading newline inside a long string is dropped by Lua, so add one explicitly
    return "[" + eq + "[\n" + s + "]" + eq + "]"


def lua_value(prop, v):
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, list) and prop in COLOR_PROPS and len(v) == 3:
        return "M.Color3.new(%s, %s, %s)" % tuple(repr(x) for x in v)
    if isinstance(v, str) and prop in ENUM_PROPS:
        return "M.Enum.%s.%s" % (ENUM_PROPS[prop], v)
    if isinstance(v, str):
        return json.dumps(v)
    return None


def project_props(project):
    """service/class path -> {prop: value} from $properties in the project file."""
    out = {}

    def walk(node, path):
        props = node.get("$properties")
        if props:
            out[tuple(path)] = props
        for k, v in node.items():
            if not k.startswith("$") and isinstance(v, dict):
                walk(v, path + [k])

    walk(project["tree"], [])
    return out


def build_tree(sourcemap, props):
    sources = []
    lines = []

    def emit(node, path):
        name = node["name"]
        cls = node["className"]
        files = [f for f in node.get("filePaths", []) if f.endswith(".luau") or f.endswith(".lua")]
        parts = ["n=%s" % json.dumps(name), "c=%s" % json.dumps(cls)]
        if files and cls in ("Script", "LocalScript", "ModuleScript"):
            with open(os.path.join(ROOT, files[0]), encoding="utf-8") as fh:
                sources.append(fh.read())
            parts.append("s=%d" % len(sources))
            parts.append("f=%s" % json.dumps(files[0]))
        p = props.get(tuple(path[1:]))
        if p:
            kv = []
            for k, v in p.items():
                lv = lua_value(k, v)
                if lv is not None:
                    kv.append("%s=%s" % (k, lv))
            parts.append("p={%s}" % ",".join(kv))
        kids = node.get("children", [])
        if kids:
            parts.append("k={" + ",".join(emit(c, path + [c["name"]]) for c in kids) + "}")
        return "{" + ",".join(parts) + "}"

    tree = emit(sourcemap, [sourcemap["name"]])
    return tree, sources


ARGS = {}


def make_bundle(scenario_path):
    sm = subprocess.run([ROJO, "sourcemap", PROJECT, "--include-non-scripts"], cwd=ROOT, capture_output=True, text=True)
    if sm.returncode != 0:
        raise SystemExit("rojo sourcemap failed: " + sm.stderr)
    sourcemap = json.loads(sm.stdout)
    with open(os.path.join(ROOT, PROJECT)) as fh:
        project = json.load(fh)
    tree, sources = build_tree(sourcemap, project_props(project))
    chunks = ["-- GENERATED by tools/headless/run.py. Offline Roblox MOCK, not Roblox.", "local M = {}"]
    mock_dir = os.path.join(HERE, "mock")
    for f in sorted(os.listdir(mock_dir)):
        if f.endswith(".luau"):
            with open(os.path.join(mock_dir, f), encoding="utf-8") as fh:
                chunks.append("do -- " + f + "\n" + fh.read() + "\nend")
    chunks.append("M.SOURCES = {" + ",\n".join(long_string(s) for s in sources) + "}")
    chunks.append("M.TREE = " + tree)
    chunks.append("M.ARGS = {" + ",".join("[%s]=%s" % (json.dumps(k), json.dumps(v)) for k, v in ARGS.items()) + "}")
    chunks.append(
        "local H = M.H\n"
        "local game, workspace, Enum, Vector3, Vector2, CFrame, Color3, UDim2, UDim, Instance, task, typeof = "
        "M.game, M.game:GetService('Workspace'), M.Enum, M.Vector3, M.Vector2, M.CFrame, M.Color3, M.UDim2, M.UDim, M.Instance, M.task, M.typeof"
    )
    lib = os.path.join(HERE, "scenarios", "_lib.luau")
    with open(lib, encoding="utf-8") as fh:
        chunks.append("do -- _lib\n" + fh.read() + "\nend")
    chunks.append("local Lib = M.Lib")
    with open(scenario_path, encoding="utf-8") as fh:
        body = fh.read()
    chunks.append(
        "do -- scenario\nlocal ok, err = xpcall(function()\n"
        + body
        + "\nend, function(e) return tostring(e) .. '\\n' .. debug.traceback() end)\n"
        + "if not ok then H.check('scenario completed without a harness error', false, err) end\nend"
    )
    chunks.append("H.finish()")
    return "\n".join(chunks)


def run(name):
    path = os.path.join(HERE, "scenarios", name + ".luau")
    if not os.path.exists(path):
        print("no such scenario: " + name)
        return False
    os.makedirs(OUT, exist_ok=True)
    bundle = make_bundle(path)
    bpath = os.path.join(OUT, "bundle_" + name + ".luau")
    with open(bpath, "w", encoding="utf-8") as fh:
        fh.write(bundle)
    print("\n######## scenario " + name)
    t0 = time.time()
    proc = subprocess.Popen([LUAU, bpath], cwd=ROOT, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    log = []
    file_name, file_buf = None, []
    passed = failed = errors = None
    for line in proc.stdout:
        line = line.rstrip("\n")
        if file_name is not None:
            if line == "@@END":
                dest = os.path.join(ROOT, file_name)
                os.makedirs(os.path.dirname(dest), exist_ok=True)
                with open(dest, "w", encoding="utf-8") as fh:
                    fh.write("\n".join(file_buf))
                print("  wrote " + file_name)
                file_name, file_buf = None, []
            else:
                file_buf.append(line)
            continue
        if line.startswith("@@FILE "):
            file_name = line[7:].strip()
            continue
        log.append(line)
        if line.startswith("RESULT "):
            parts = line.split()
            passed, failed, errors = int(parts[1]), int(parts[3]), int(parts[5])
        print(line)
    proc.wait()
    dt = time.time() - t0
    with open(os.path.join(OUT, name + ".log"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(log) + "\n")
    ok = proc.returncode == 0 and failed == 0 and errors == 0
    status = "OK" if ok else "PROBLEMS"
    print("######## %s: %s (%s passed, %s failed, %s runtime errors, exit %d, %.1fs wall)" % (name, status, passed, failed, errors, proc.returncode, dt))
    return ok


def main():
    args = []
    it = iter(sys.argv[1:])
    for a in it:
        if a == "--set":
            k, _, v = next(it).partition("=")
            ARGS[k] = v
        elif not a.startswith("--"):
            args.append(a)
    scen_dir = os.path.join(HERE, "scenarios")
    all_names = sorted(f[:-5] for f in os.listdir(scen_dir) if f.endswith(".luau") and not f.startswith("_"))
    if "--list" in sys.argv:
        print("\n".join(all_names))
        return 0
    names = args or all_names
    results = {n: run(n) for n in names}
    print("\n######## summary (offline mock, not Roblox)")
    for n, ok in results.items():
        print("  %-28s %s" % (n, "OK" if ok else "PROBLEMS"))
    return 0 if all(results.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
